#pragma once

class GoAttack {
public:
	DefineStaticMethod(FUBI_NetToInstance, 0x44a0c6, GoAttack*, Params(unsigned long unk1, FuBi::Cookie__** unk2), Args(unk1, unk2));
	DefineStaticMethod(FUBI_InstanceToNet, 0x44a0bd, unsigned long, Params(GoAttack* unk1), Args(unk1));
	DefineConstMethod(GetAmmoAlwaysAttached, 0x937afe, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetAmmoAppearsJIT, 0x937ac5, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetAmmoAttachesToWeapon, 0x937a8c, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetForceCriticals, 0x44a01c, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetIsDualWield, 0x44a07e, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetIsMelee, 0x44a041, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetIsOneShot, 0x44a060, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetIsProjectile, 0x44a04a, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetIsThrown, 0x44a088, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetIsTwoHanded, 0x44a06a, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetIsWeapon, 0x44a054, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetIsWieldedWeapon, 0x44a074, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetMarkTargetFire, 0x44abce, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetMonsterAddBaseDamage, 0x937b70, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetMultiAttack, 0x44a023, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetRequiresLineOfSight, 0x44a03a, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetUseAimingError, 0x9379e3, bool, NO_PARAMS, NO_ARGS);
	DefineMethod(IsInProjectileRange, 0x93840c, bool, Params(float unk1, const SiegePos& unk2), Args(unk1, unk2));
	DefineMethod(GetShooter, 0x936f05, Go*, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetAmmoAttachBone, 0x937a55, const gpbstring<char>&, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetDamageToType, 0x44abb9, const gpbstring<char>&, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetSkillClass, 0x937973, const gpbstring<char>&, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetAmmoCloneSource, 0x449ffe, const Goid_*, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetAmmoReady, 0x44a002, const Goid_*, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetLastFiredAmmo, 0x44a092, const Goid_*, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetProjectileLauncher, 0x449ffa, const Goid_*, NO_PARAMS, NO_ARGS);
	DefineMethod(SPrepareAmmo, 0x9376e2, const Goid_*, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetAttackClass, 0x449fe5, eAttackClass, NO_PARAMS, NO_ARGS);
	DefineMethod(GetDamageType, 0x936f1a, eDamageType, NO_PARAMS, NO_ARGS);
	DefineMethod(ComputeAimingAngle, 0x93765e, float, Params(const Goid_* unk1, const SiegePos& unk2, const SiegePos& unk3, float unk4), Args(unk1, unk2, unk3, unk4));
	DefineMethod(ComputeAimingAngle, 0x937fbe, float, Params(const SiegePos& unk1, const SiegePos& unk2, float unk3), Args(unk1, unk2, unk3));
	DefineConstMethod(GetAimingErrorBonus, 0x44ab57, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetAimingErrorX, 0x44a0af, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetAimingErrorY, 0x44a0b6, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetAmountDamageToType, 0x44abc0, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetAreaDamageRadius, 0x9379aa, float, NO_PARAMS, NO_ARGS);
	DefineMethod(GetAttackRange, 0x93906a, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetChanceForAimingError, 0x44ab50, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetChanceToHitBonus, 0x44ab3b, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetChanceToHitBonusMelee, 0x44ab42, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetChanceToHitBonusRanged, 0x44ab49, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetChanceToPenetrate, 0x44abd5, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetCMagicExpPercent, 0x44ab7a, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetCriticalChanceMeleeBonusPercent, 0x44aabd, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetCriticalChanceRangedBonusPercent, 0x44aac4, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetCriticalDamageBonusPercent, 0x44aaa8, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetCriticalDamageMeleeBonusPercent, 0x44aaaf, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetCriticalDamageRangedBonusPercent, 0x44aab6, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetCustomEffectDamageChance, 0x939c8a, float, Params(const char* unk1, const Goid_* unk2), Args(unk1, unk2));
	DefineConstMethod(GetCustomEffectDamageMax, 0x939cee, float, Params(const char* unk1, const Goid_* unk2), Args(unk1, unk2));
	DefineConstMethod(GetCustomEffectDamageMin, 0x939cd1, float, Params(const char* unk1, const Goid_* unk2), Args(unk1, unk2));
	DefineConstMethod(GetDamageBonusMaxCMagic, 0x44aa69, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetDamageBonusMaxMelee, 0x44aa4e, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetDamageBonusMaxNMagic, 0x44aa7e, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetDamageBonusMaxRanged, 0x44aa5a, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetDamageBonusMinCMagic, 0x44aa62, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetDamageBonusMinMelee, 0x44aa4a, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetDamageBonusMinNMagic, 0x44aa77, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetDamageBonusMinRanged, 0x44aa56, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetDamageMax, 0x44aa27, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetDamageMin, 0x44aa0c, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetDamageMultiplierCMagic, 0x44aa70, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetDamageMultiplierMelee, 0x44aa52, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetDamageMultiplierNMagic, 0x44aa85, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetDamageMultiplierRanged, 0x44aa5e, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetDamageToUndead, 0x44abc7, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetDeathDamageBonusPercent, 0x44aaa1, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetExperienceBonus, 0x44ab5e, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetFireDamageBonusPercent, 0x44aa93, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetIceDamageBonusPercent, 0x44aa8c, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetLifeBonusAmount, 0x44abab, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetLifeStealAmount, 0x44ab81, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetLifeStealAmountMelee, 0x44ab88, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetLifeStealAmountRanged, 0x44ab8f, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetLightningDamageBonusPercent, 0x44aa9a, float, NO_PARAMS, NO_ARGS);
	DefineMethod(GetMagicPowerDamageBonusPercent, 0x44aa46, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetManaBonusAmount, 0x44abb2, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetManaDamageValueMelee, 0x44aad9, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetManaDamageValueRanged, 0x44aacb, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetManaDrainValueMelee, 0x44aae0, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetManaDrainValueRanged, 0x44aad2, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetManaStealAmount, 0x44ab96, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetManaStealAmountMelee, 0x44ab9d, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetManaStealAmountRanged, 0x44aba4, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetMeleeExpPercent, 0x44ab65, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetNMagicExpPercent, 0x44ab73, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetPiercingDamageChance, 0x44aae7, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetPiercingDamageChanceAmount, 0x44aafc, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetPiercingDamageChanceAmountMelee, 0x44ab03, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetPiercingDamageChanceAmountRanged, 0x44ab0a, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetPiercingDamageChanceMelee, 0x44aaee, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetPiercingDamageChanceRanged, 0x44aaf5, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetPiercingDamageMax, 0x44ab18, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetPiercingDamageMeleeMax, 0x44ab26, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetPiercingDamageMeleeMin, 0x44ab1f, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetPiercingDamageMin, 0x44ab11, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetPiercingDamageRangedMax, 0x44ab34, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetPiercingDamageRangedMin, 0x44ab2d, float, NO_PARAMS, NO_ARGS);
	DefineMethod(GetPowerDamageBonusPercent, 0x44aa42, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetRangedExpPercent, 0x44ab6c, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetReloadDelay, 0x449fe9, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetWeaponErrorRange, 0x937a1c, float, NO_PARAMS, NO_ARGS);
	DefineMethod(ComputeFiringPos, 0x9382f2, SiegePos&, NO_PARAMS, NO_ARGS);
	DefineMethod(ComputeTargetPos, 0x44a099, SiegePos&, Params(const Goid_* unk1), Args(unk1));
	DefineMethod(ComputeTimedTargetPos, 0x937e18, SiegePos&, Params(const Goid_* unk1, double unk2), Args(unk1, unk2));
	DefineMethod(ComputeAimingError, 0x937f2d, void, NO_PARAMS, NO_ARGS);
	DefineMethod(RCLaunchAmmo, 0x9385b1, void, Params(Go* unk1, const Goid_* unk2, SiegePos unk3, vector_3 unk4, unsigned long unk5), Args(unk1, unk2, unk3, unk4, unk5));
	DefineMethod(RCSetDamageMaxNatural, 0x937573, void, Params(float unk1, unsigned long unk2), Args(unk1, unk2));
	DefineMethod(RCSetDamageMinNatural, 0x937488, void, Params(float unk1, unsigned long unk2), Args(unk1, unk2));
	DefineMethod(SetDamageMax, 0x44b30f, void, Params(float unk1), Args(unk1));
	DefineMethod(SetDamageMaxNatural, 0x44aa2b, void, Params(float unk1), Args(unk1));
	DefineMethod(SetDamageMin, 0x44b302, void, Params(float unk1), Args(unk1));
	DefineMethod(SetDamageMinNatural, 0x44aa10, void, Params(float unk1), Args(unk1));
	DefineMethod(SetMultiAttack, 0x44a02a, void, Params(bool unk1), Args(unk1));
	DefineMethod(SetProjectileLauncher, 0x449fed, void, Params(const Goid_* unk1), Args(unk1));
	DefineMethod(SLaunchAmmo, 0x93857a, void, Params(float unk1, const SiegePos& unk2, const SiegePos& unk3, float unk4, float unk5, const Goid_* unk6), Args(unk1, unk2, unk3, unk4, unk5, unk6));
	DefineMethod(SLaunchSpecifiedAmmo, 0x93848e, void, Params(const Goid_* unk1, float unk2, const SiegePos& unk3, const SiegePos& unk4, float unk5, float unk6, const Goid_* unk7, const Goid_* unk8), Args(unk1, unk2, unk3, unk4, unk5, unk6, unk7, unk8));
	DefineMethod(SSetDamageMaxNatural, 0x937be7, void, Params(float unk1), Args(unk1));
	DefineMethod(SSetDamageMinNatural, 0x937ba9, void, Params(float unk1), Args(unk1));
	DefineMethod(SSetForceCriticals, 0x936ef5, void, Params(bool unk1), Args(unk1));
	DefineMethod(SUnprepareAmmo, 0x937765, void, NO_PARAMS, NO_ARGS);
};
