#pragma once

#include "Enums.h"

struct MoodSetting {
	DefineStaticMethod(FUBI_PodGetSize, 0x4126dc, unsigned int, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetbAmbientRandom, 0x4128da, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetbDriftEnabled, 0x41283d, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetbFogEnabled, 0x41274f, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetbFrustumEnabled, 0x41270b, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetbInterior, 0x4126f6, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetbLightning, 0x4127f9, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetbMusicEnabled, 0x4128c9, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetbPartyLightEnabled, 0x412977, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetbRainEnabled, 0x4127c6, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetbSkyboxEnabled, 0x41291f, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetbSnowEnabled, 0x41280a, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetbStandardRandom, 0x4128f1, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetbWindEnabled, 0x412896, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetbackTexture, 0x412959, const gpbstring<char>&, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetbottomTexture, 0x41293d, const gpbstring<char>&, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetdriftTextures, 0x412870, const gpbstring<char>&, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetenvironEffect, 0x412707, const gpbstring<char>&, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetfrontTexture, 0x412952, const gpbstring<char>&, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetleftTexture, 0x412944, const gpbstring<char>&, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetmoodName, 0x4126e2, const gpbstring<char>&, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetrightTexture, 0x41294b, const gpbstring<char>&, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GettopTexture, 0x412936, const gpbstring<char>&, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetmoodRoomType, 0x412908, eMoodRoomType, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetdriftDensity, 0x41284e, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetdriftLowDetDensity, 0x41285f, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetdriftMaxSize, 0x412885, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetdriftMinSize, 0x412874, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetfogDensity, 0x4127b5, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetfogFarDist, 0x412771, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetfogLowDetFarDist, 0x412793, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetfogLowDetNearDist, 0x412782, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetfogNearDist, 0x412760, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetfrustumDepth, 0x41273e, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetfrustumHeight, 0x41272d, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetfrustumWidth, 0x41271c, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GethorizonOffset, 0x412960, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetpartyLightInnerRad, 0x41298e, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetpartyLightOuterRad, 0x4129a5, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetpartyVertOffset, 0x4129bc, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetrainDensity, 0x4127d7, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetrainLowDetDensity, 0x4127e8, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetsnowDensity, 0x41281b, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetsnowLowDetDensity, 0x41282c, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GettransitionTime, 0x4126e5, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetwindDirection, 0x4128b8, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetwindVelocity, 0x4128a7, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetfogColor, 0x4127a4, unsigned long, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetpartyLightColor, 0x4129d3, unsigned long, NO_PARAMS, NO_ARGS);
	DefineMethod(SetbackTexture, 0x419c07, void, Params(const gpbstring<char>& unk1), Args(unk1));
	DefineMethod(SetbAmbientRandom, 0x4128e1, void, Params(bool unk1), Args(unk1));
	DefineMethod(SetbDriftEnabled, 0x412841, void, Params(bool unk1), Args(unk1));
	DefineMethod(SetbFogEnabled, 0x412753, void, Params(bool unk1), Args(unk1));
	DefineMethod(SetbFrustumEnabled, 0x41270f, void, Params(bool unk1), Args(unk1));
	DefineMethod(SetbInterior, 0x4126fa, void, Params(bool unk1), Args(unk1));
	DefineMethod(SetbLightning, 0x4127fd, void, Params(bool unk1), Args(unk1));
	DefineMethod(SetbMusicEnabled, 0x4128cd, void, Params(bool unk1), Args(unk1));
	DefineMethod(SetbottomTexture, 0x419ba3, void, Params(const gpbstring<char>& unk1), Args(unk1));
	DefineMethod(SetbPartyLightEnabled, 0x41297e, void, Params(bool unk1), Args(unk1));
	DefineMethod(SetbRainEnabled, 0x4127ca, void, Params(bool unk1), Args(unk1));
	DefineMethod(SetbSkyboxEnabled, 0x412926, void, Params(bool unk1), Args(unk1));
	DefineMethod(SetbSnowEnabled, 0x41280e, void, Params(bool unk1), Args(unk1));
	DefineMethod(SetbStandardRandom, 0x4128f8, void, Params(bool unk1), Args(unk1));
	DefineMethod(SetbWindEnabled, 0x41289a, void, Params(bool unk1), Args(unk1));
	DefineMethod(SetdriftDensity, 0x412852, void, Params(float unk1), Args(unk1));
	DefineMethod(SetdriftLowDetDensity, 0x412863, void, Params(float unk1), Args(unk1));
	DefineMethod(SetdriftMaxSize, 0x412889, void, Params(float unk1), Args(unk1));
	DefineMethod(SetdriftMinSize, 0x412878, void, Params(float unk1), Args(unk1));
	DefineMethod(SetdriftTextures, 0x419b74, void, Params(const gpbstring<char>& unk1), Args(unk1));
	DefineMethod(SetenvironEffect, 0x419b5e, void, Params(const gpbstring<char>& unk1), Args(unk1));
	DefineMethod(SetfogColor, 0x4127a8, void, Params(unsigned long unk1), Args(unk1));
	DefineMethod(SetfogDensity, 0x4127b9, void, Params(float unk1), Args(unk1));
	DefineMethod(SetfogFarDist, 0x412775, void, Params(float unk1), Args(unk1));
	DefineMethod(SetfogLowDetFarDist, 0x412797, void, Params(float unk1), Args(unk1));
	DefineMethod(SetfogLowDetNearDist, 0x412786, void, Params(float unk1), Args(unk1));
	DefineMethod(SetfogNearDist, 0x412764, void, Params(float unk1), Args(unk1));
	DefineMethod(SetfrontTexture, 0x419bee, void, Params(const gpbstring<char>& unk1), Args(unk1));
	DefineMethod(SetfrustumDepth, 0x412742, void, Params(float unk1), Args(unk1));
	DefineMethod(SetfrustumHeight, 0x412731, void, Params(float unk1), Args(unk1));
	DefineMethod(SetfrustumWidth, 0x412720, void, Params(float unk1), Args(unk1));
	DefineMethod(SethorizonOffset, 0x412967, void, Params(float unk1), Args(unk1));
	DefineMethod(SetleftTexture, 0x419bbc, void, Params(const gpbstring<char>& unk1), Args(unk1));
	DefineMethod(SetmoodName, 0x419b4b, void, Params(const gpbstring<char>& unk1), Args(unk1));
	DefineMethod(SetmoodRoomType, 0x41290f, void, Params(eMoodRoomType unk1), Args(unk1));
	DefineMethod(SetpartyLightColor, 0x4129da, void, Params(unsigned long unk1), Args(unk1));
	DefineMethod(SetpartyLightInnerRad, 0x412995, void, Params(float unk1), Args(unk1));
	DefineMethod(SetpartyLightOuterRad, 0x4129ac, void, Params(float unk1), Args(unk1));
	DefineMethod(SetpartyVertOffset, 0x4129c3, void, Params(float unk1), Args(unk1));
	DefineMethod(SetrainDensity, 0x4127db, void, Params(float unk1), Args(unk1));
	DefineMethod(SetrainLowDetDensity, 0x4127ec, void, Params(float unk1), Args(unk1));
	DefineMethod(SetrightTexture, 0x419bd5, void, Params(const gpbstring<char>& unk1), Args(unk1));
	DefineMethod(SetsnowDensity, 0x41281f, void, Params(float unk1), Args(unk1));
	DefineMethod(SetsnowLowDetDensity, 0x412830, void, Params(float unk1), Args(unk1));
	DefineMethod(SettopTexture, 0x419b8a, void, Params(const gpbstring<char>& unk1), Args(unk1));
	DefineMethod(SettransitionTime, 0x4126e9, void, Params(float unk1), Args(unk1));
	DefineMethod(SetwindDirection, 0x4128bc, void, Params(float unk1), Args(unk1));
	DefineMethod(SetwindVelocity, 0x4128ab, void, Params(float unk1), Args(unk1));
};
