#pragma once

#include "Enums.h"

class QuestManager {
public:
	DefineSingleton(QuestManager, 0x414300);

	DefineConstMethod(GetLastActivatedAct, 0x8884c1, const char*, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetLastActivatedQuest, 0x8884d4, const char*, NO_PARAMS, NO_ARGS);
	DefineMethod(ActivateQuestOrLoreItem, 0x88d393, bool, Params(const gpbstring<char>& unk1, Go* unk2), Args(unk1, unk2));
	DefineMethod(AreAllWorldTasksComplete, 0x412ba5, bool, Params(const char* unk1), Args(unk1));
	DefineConstMethod(AreAllWorldTasksInState, 0x88a5ef, bool, Params(const char* unk1, eQuestState unk2), Args(unk1, unk2));
	DefineConstMethod(GetPartyMemberAccepted, 0x888c58, bool, Params(const Go* unk1), Args(unk1));
	DefineConstMethod(GetPartyMemberAllowRejoin, 0x8892b4, bool, Params(const Go* unk1), Args(unk1));
	DefineConstMethod(GetPartyMemberDeclined, 0x888def, bool, Params(const Go* unk1), Args(unk1));
	DefineConstMethod(GetPartyMemberDisband, 0x888f86, bool, Params(const Go* unk1), Args(unk1));
	DefineConstMethod(GetPartyMemberWasDisbanded, 0x88911d, bool, Params(const Go* unk1), Args(unk1));
	DefineConstMethod(GetWasPartyMember, 0x88944b, bool, Params(const Go* unk1), Args(unk1));
	DefineMethod(HasLocalActBeenActivated, 0x412cc4, bool, Params(const char* unk1), Args(unk1));
	DefineMethod(HasLocalActBeenViewed, 0x412d0f, bool, Params(const char* unk1), Args(unk1));
	DefineMethod(HasLocalLoreBeenViewed, 0x412d41, bool, Params(const char* unk1), Args(unk1));
	DefineMethod(HasLocalQuestBeenActivated, 0x412cdd, bool, Params(const char* unk1), Args(unk1));
	DefineMethod(HasLocalQuestBeenViewed, 0x412d28, bool, Params(const char* unk1), Args(unk1));
	DefineMethod(HasLocalTaskBeenActivated, 0x412cf6, bool, Params(const char* unk1), Args(unk1));
	DefineMethod(HasWorldActBeenActivated, 0x412bb6, bool, Params(const char* unk1), Args(unk1));
	DefineMethod(HasWorldQuestBeenActivated, 0x412bcf, bool, Params(const char* unk1), Args(unk1));
	DefineMethod(HasWorldTaskBeenActivated, 0x412be8, bool, Params(const char* unk1), Args(unk1));
	DefineMethod(IsKillCountPassed, 0x88a705, bool, Params(const gpbstring<char>& unk1), Args(unk1));
	DefineMethod(IsLocalActActive, 0x412d5a, bool, Params(const char* unk1), Args(unk1));
	DefineMethod(IsLocalActComplete, 0x412da6, bool, Params(const char* unk1), Args(unk1));
	DefineMethod(IsLocalLoreItemFound, 0x412e1d, bool, Params(const char* unk1), Args(unk1));
	DefineMethod(IsLocalLoreItemViewed, 0x412e36, bool, Params(const char* unk1), Args(unk1));
	DefineMethod(IsLocalMapLocationFound, 0x412e88, bool, Params(int unk1), Args(unk1));
	DefineMethod(IsLocalMapLocationViewed, 0x412ea1, bool, Params(int unk1), Args(unk1));
	DefineMethod(IsLocalQuestActive, 0x412d70, bool, Params(const char* unk1), Args(unk1));
	DefineMethod(IsLocalQuestComplete, 0x412dbd, bool, Params(const char* unk1), Args(unk1));
	DefineMethod(IsLocalQuestItemFound, 0x412deb, bool, Params(const char* unk1), Args(unk1));
	DefineMethod(IsLocalQuestItemViewed, 0x412e04, bool, Params(const char* unk1), Args(unk1));
	DefineMethod(IsLocalTaskActive, 0x412d90, bool, Params(const char* unk1), Args(unk1));
	DefineMethod(IsLocalTaskComplete, 0x412dd4, bool, Params(const char* unk1), Args(unk1));
	DefineConstMethod(IsQuestOrLoreItem, 0x88a695, bool, Params(const gpbstring<char>& unk1), Args(unk1));
	DefineMethod(IsTeleportLocationActivated, 0x412eba, bool, Params(const char* unk1), Args(unk1));
	DefineMethod(IsWorldActActive, 0x412c01, bool, Params(const char* unk1), Args(unk1));
	DefineMethod(IsWorldActComplete, 0x412c4d, bool, Params(const char* unk1), Args(unk1));
	DefineMethod(IsWorldLoreItemFound, 0x412cab, bool, Params(const char* unk1), Args(unk1));
	DefineMethod(IsWorldQuestActive, 0x412c17, bool, Params(const char* unk1), Args(unk1));
	DefineMethod(IsWorldQuestComplete, 0x412c64, bool, Params(const char* unk1), Args(unk1));
	DefineMethod(IsWorldQuestItemFound, 0x412c92, bool, Params(const char* unk1), Args(unk1));
	DefineMethod(IsWorldTaskActive, 0x412c37, bool, Params(const char* unk1), Args(unk1));
	DefineMethod(IsWorldTaskComplete, 0x412c7b, bool, Params(const char* unk1), Args(unk1));
	DefineConstMethod(GetQuestNameByTaskName, 0x88a5ab, const char*, Params(const char* unk1), Args(unk1));
	DefineConstMethod(GetTemplateEntryType, 0x88a66c, eEntryType, Params(const gpbstring<char>& unk1), Args(unk1));
	DefineConstMethod(GetLocalActState, 0x889a8b, eQuestState, Params(const char* unk1), Args(unk1));
	DefineConstMethod(GetLocalLoreState, 0x889c30, eQuestState, Params(const char* unk1), Args(unk1));
	DefineConstMethod(GetLocalQuestState, 0x889b40, eQuestState, Params(const char* unk1), Args(unk1));
	DefineConstMethod(GetLocalTaskState, 0x889bb8, eQuestState, Params(const char* unk1), Args(unk1));
	DefineMethod(GetMapLocationState, 0x889d55, eQuestState, Params(unsigned long unk1), Args(unk1));
	DefineConstMethod(GetTeleportLocationState, 0x888abe, eQuestState, Params(const char* unk1), Args(unk1));
	DefineConstMethod(GetWorldActState, 0x889a4f, eQuestState, Params(const char* unk1), Args(unk1));
	DefineConstMethod(GetWorldLoreState, 0x889bf4, eQuestState, Params(const char* unk1), Args(unk1));
	DefineConstMethod(GetWorldQuestState, 0x889b04, eQuestState, Params(const char* unk1), Args(unk1));
	DefineConstMethod(GetWorldTaskState, 0x889b7c, eQuestState, Params(const char* unk1), Args(unk1));
	DefineConstMethod(GetActCount, 0x4142f4, int, NO_PARAMS, NO_ARGS); // LocalJournal->GetInt("h_curr", 0);
	DefineMethod(GetHandbookChapter, 0x887c7b, int, NO_PARAMS, NO_ARGS);
	DefineMethod(GetKillCount, 0x88a6aa, int, Params(const gpbstring<char>& unk1), Args(unk1));
	DefineConstMethod(GetQuestIndexByQuestName, 0x88a5c5, int, Params(const char* unk1), Args(unk1));
	DefineConstMethod(GetQuestTaskCount, 0x88a5de, int, Params(const char* unk1), Args(unk1));
	DefineMethod(GetActDataByActIndex, 0x887c53, ActData*, Params(unsigned int unk1), Args(unk1));
	DefineMethod(GetActDataByActName, 0x889ac7, ActData*, Params(const char* unk1), Args(unk1));
	DefineMethod(RCAddToKillCount, 0x88d3ff, FuBi::Cookie__*, Params(const gpbstring<char>& unk1, unsigned long unk2), Args(unk1, unk2));
	DefineMethod(RCSetActState, 0x88a433, FuBi::Cookie__*, Params(const char* unk1, eQuestState unk2, unsigned long unk3), Args(unk1, unk2, unk3));
	DefineMethod(RCSetHandbookChapter, 0x888987, FuBi::Cookie__*, Params(int unk1, unsigned long unk2), Args(unk1, unk2));
	DefineMethod(RCSetLoreState, 0x88be52, FuBi::Cookie__*, Params(const char* unk1, eQuestState unk2, unsigned long unk3, bool unk4), Args(unk1, unk2, unk3, unk4));
	DefineMethod(RCSetQuestState, 0x88cce5, FuBi::Cookie__*, Params(const char* unk1, eQuestState unk2, unsigned long unk3), Args(unk1, unk2, unk3));
	DefineMethod(RCSetTaskState, 0x88bd54, FuBi::Cookie__*, Params(const char* unk1, eQuestState unk2, unsigned long unk3), Args(unk1, unk2, unk3));
	DefineMethod(RCSetTeleportLocationState, 0x889704, FuBi::Cookie__*, Params(const char* unk1, eQuestState unk2, unsigned long unk3), Args(unk1, unk2, unk3));
	DefineMethod(RSSetActState, 0x88b441, FuBi::Cookie__*, Params(const char* unk1, eQuestState unk2, unsigned long unk3), Args(unk1, unk2, unk3));
	DefineMethod(RSSetActState, 0x88bca7, FuBi::Cookie__*, Params(const char* unk1, eQuestState unk2), Args(unk1, unk2));
	DefineMethod(RSSetLoreState, 0x88ce07, FuBi::Cookie__*, Params(const char* unk1, eQuestState unk2, bool unk3), Args(unk1, unk2, unk3));
	DefineMethod(RSSetLoreState, 0x88c536, FuBi::Cookie__*, Params(const char* unk1, eQuestState unk2, unsigned long unk3, bool unk4), Args(unk1, unk2, unk3, unk4));
	DefineMethod(RSSetQuestState, 0x88d22d, FuBi::Cookie__*, Params(const char* unk1, eQuestState unk2, unsigned long unk3), Args(unk1, unk2, unk3));
	DefineMethod(RSSetQuestState, 0x88d563, FuBi::Cookie__*, Params(const char* unk1, eQuestState unk2), Args(unk1, unk2));
	DefineMethod(RSSetTaskState, 0x88c3d0, FuBi::Cookie__*, Params(const char* unk1, eQuestState unk2, unsigned long unk3), Args(unk1, unk2, unk3));
	DefineMethod(RSSetTaskState, 0x88cde3, FuBi::Cookie__*, Params(const char* unk1, eQuestState unk2), Args(unk1, unk2));
	DefineMethod(RSSetTeleportLocationState, 0x889dca, FuBi::Cookie__*, Params(const char* unk1, eQuestState unk2, unsigned long unk3), Args(unk1, unk2, unk3));
	DefineMethod(RSSetTeleportLocationState, 0x88a18e, FuBi::Cookie__*, Params(const char* unk1, eQuestState unk2), Args(unk1, unk2));
	DefineConstMethod(GetQuestDataByQuestName, 0x88a52f, QuestData*, Params(const char* unk1), Args(unk1));
	DefineConstMethod(GetQuestDataByTaskName, 0x88a56d, QuestData*, Params(const char* unk1), Args(unk1));
	DefineConstMethod(GetTaskDataByTaskName, 0x88a62e, TaskData*, Params(const char* unk1), Args(unk1));
	DefineMethod(RSActivateAct, 0x412aa9, void, Params(const char* unk1), Args(unk1));
	DefineMethod(RSActivateLore, 0x412adc, void, Params(const char* unk1), Args(unk1));
	DefineMethod(RSActivateQuest, 0x412aba, void, Params(const char* unk1), Args(unk1));
	DefineMethod(RSActivateTask, 0x412acb, void, Params(const char* unk1), Args(unk1));
	DefineMethod(RSCompleteAct, 0x412aef, void, Params(const char* unk1), Args(unk1));
	DefineMethod(RSCompleteQuest, 0x412b00, void, Params(const char* unk1), Args(unk1));
	DefineMethod(RSCompleteTask, 0x412b11, void, Params(const char* unk1), Args(unk1));
	DefineMethod(RSDeactivateAct, 0x412b22, void, Params(const char* unk1), Args(unk1));
	DefineMethod(RSDeactivateLore, 0x412b55, void, Params(const char* unk1), Args(unk1));
	DefineMethod(RSDeactivateQuest, 0x412b33, void, Params(const char* unk1), Args(unk1));
	DefineMethod(RSDeactivateTask, 0x412b44, void, Params(const char* unk1), Args(unk1));
	DefineMethod(RSSetMapLocationState, 0x889c6c, void, Params(unsigned long unk1, eQuestState unk2, unsigned long unk3), Args(unk1, unk2, unk3));
	DefineMethod(RSSetMapLocationStateFound, 0x412e63, void, Params(int unk1, unsigned long unk2), Args(unk1, unk2));
	DefineMethod(RSSetMapLocationStateMissing, 0x412e4f, void, Params(int unk1, unsigned long unk2), Args(unk1, unk2));
	DefineMethod(RSSetPartyMemberAccepted, 0x888b10, void, Params(const Go* unk1, bool unk2, unsigned long unk3), Args(unk1, unk2, unk3));
	DefineMethod(RSSetPartyMemberAllowRejoin, 0x88916c, void, Params(const Go* unk1, bool unk2, unsigned long unk3), Args(unk1, unk2, unk3));
	DefineMethod(RSSetPartyMemberDeclined, 0x888ca7, void, Params(const Go* unk1, bool unk2, unsigned long unk3), Args(unk1, unk2, unk3));
	DefineMethod(RSSetPartyMemberDisband, 0x888e3e, void, Params(const Go* unk1, bool unk2, unsigned long unk3), Args(unk1, unk2, unk3));
	DefineMethod(RSSetPartyMemberWasDisbanded, 0x888fd5, void, Params(const Go* unk1, bool unk2, unsigned long unk3), Args(unk1, unk2, unk3));
	DefineMethod(RSSetWasPartyMember, 0x889303, void, Params(const Go* unk1, bool unk2, unsigned long unk3), Args(unk1, unk2, unk3));
	DefineMethod(SAddToKillCount, 0x88d60c, void, Params(const gpbstring<char>& unk1, unsigned long unk2), Args(unk1, unk2));
	DefineMethod(SAddToTeamKillCount, 0x88d587, void, Params(const gpbstring<char>& unk1, unsigned long unk2), Args(unk1, unk2));
	DefineMethod(SetAllActStates, 0x88a161, void, Params(eQuestState unk1, bool unk2), Args(unk1, unk2));
	DefineMethod(SetAllLoreStates, 0x88b891, void, Params(eQuestState unk1, bool unk2), Args(unk1, unk2));
	DefineMethod(SetAllQuestStates, 0x88c394, void, Params(eQuestState unk1, bool unk2), Args(unk1, unk2));
	DefineMethod(SetHandbookChapter, 0x888472, void, Params(int unk1, bool unk2), Args(unk1, unk2));
	DefineMethod(SetMapLocationState, 0x889ce1, void, Params(unsigned long unk1, eQuestState unk2), Args(unk1, unk2));
	DefineMethod(SetMapLocationStateViewed, 0x412e77, void, Params(int unk1), Args(unk1));
	DefineMethod(SetQuestState, 0x88c283, void, Params(const char* unk1, eQuestState unk2, bool unk3, bool unk4), Args(unk1, unk2, unk3, unk4));
	DefineMethod(SetTaskState, 0x88b5ec, void, Params(const char* unk1, eQuestState unk2, bool unk3, bool unk4), Args(unk1, unk2, unk3, unk4));
	DefineMethod(SetTeleportLocationState, 0x888a80, void, Params(const char* unk1, eQuestState unk2), Args(unk1, unk2));
	DefineMethod(SSetHandbookChapter, 0x8896fb, void, Params(int unk1, unsigned long unk2), Args(unk1, unk2));
	DefineMethod(SSetTeamHandbookChapter, 0x889691, void, Params(int unk1, unsigned long unk2), Args(unk1, unk2));
	DefineMethod(StartFlashingJournalIcon, 0x8897fe, void, NO_PARAMS, NO_ARGS);
	DefineMethod(StopFlashingJournalIcon, 0x887c8e, void, NO_PARAMS, NO_ARGS);
	DefineMethod(SyncFlashingJournalIcon, 0x88985f, void, NO_PARAMS, NO_ARGS);
	DefineMethod(ViewedAct, 0x412b68, void, Params(const char* unk1), Args(unk1));
	DefineMethod(ViewedLore, 0x412b90, void, Params(const char* unk1), Args(unk1));
	DefineMethod(ViewedQuest, 0x412b7b, void, Params(const char* unk1), Args(unk1));

	// 0x00
	int i0x00;
	// 0x04
	int i0x04; // GetActCount -> (i0x04 - i0x00) / sizeof(ActData)
};
