#pragma once

enum AppResult : int {
	RES_OK = 0,
	RES_ERR_EXE_NOT_FOUND,
	RES_ERR_EXE_INVALID_CRC,
	RES_ERR_DLL_NOT_FOUND,
	RES_ERR_DLL_INVALID_CRC,
	RES_ERR_CREATE_PROCESS_FAILED,
	RES_ERR_CREATE_PROCESS_ELEVATION_REQUIRED,
	RES_ERR_GET_EXIT_CODE_PROCESS_FAILED,
	RES_ERR_RESUME_THREAD_FAILED,
	RES_ERR_VIRTUAL_ALLOC_FAILED,
	RES_ERR_VIRTUAL_FREE_FAILED,
	RES_ERR_WRITE_PROCESS_MEMORY_FAILED,
	RES_ERR_KERNEL32,
	RES_ERR_CREATE_REMOTE_THREAD_FAILED,
	RES_ERR_REMOTE_THREAD_ABANDONED,
	RES_ERR_REMOTE_THREAD_TIMED_OUT,
	RES_ERR_UNKNOWN,
};

const wchar_t* AppResultToString(AppResult result);

AppResult AllocAndWriteProcessMemory(HANDLE hProcess, LPVOID address, SIZE_T size, LPCVOID buffer, LPVOID* memoryPtrOut = NULL);
int FreeProcessMemory(HANDLE hProcess, LPVOID address);
AppResult LoadRemoteDll(HANDLE hProcess, const char* remoteLibraryName, DWORD timeout);
