#pragma once

#include "Enums.h"
#include "FuBi.h"
#include "GPGSound.h"
#include "MessageDispatch.h"

class GoActor;
class GoAspect;
class GoAttack;
class GoBody;
class GoCoach;
class GoCommon;
class GoComponent;
class GoConversation;
class GoCorpse;
class GoDefend;
class GoFader;
class GoFollower;
class GoGold;
class GoGui;
class GoHire;
class GoInventory;
class GoMagic;
class GoMind;
class GoParty;
class GoPet;
class GoPhysics;
class GoPlacement;
class GoPotion;
class GoProxy;
class GoStash;
class GoStore;
class GoZone;
class Player;
struct FrustumId_;
struct Goid_;
struct GopColl;
struct PlayerId_;
struct RegionId_;
struct Scid_;

class Go {
public:
	DefineStaticMethod(FUBI_NetToInstance, 0x50316d, Go*, Params(unsigned long unk1, FuBi::Cookie__** unk2), Args(unk1, unk2));
	DefineStaticMethod(FUBI_InstanceToNet, 0x503164, unsigned long, Params(Go* unk1), Args(unk1));
	DefineMethod(Deselect, 0x472f3a, bool, NO_PARAMS, NO_ARGS);
	DefineMethod(DoesShareFrustum, 0x7b1970, bool, Params(Go* unk1), Args(unk1));
	DefineMethod(GetComponentBool, 0x7b6b53, bool, Params(const char* unk1, const char* unk2, bool unk3), Args(unk1, unk2, unk3));
	DefineMethod(GetComponentBool, 0x502f8d, bool, Params(const char* unk1, const char* unk2), Args(unk1, unk2));
	DefineConstMethod(HasActor, 0x43d96c, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(HasAspect, 0x428541, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(HasAttack, 0x44a6f4, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(HasBody, 0x472f8a, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(HasChild, 0x7b4fc3, bool, Params(const Go* unk1), Args(unk1));
	DefineConstMethod(HasChild, 0x7b2ebf, bool, Params(const Goid_* unk1), Args(unk1));
	DefineConstMethod(HasCoach, 0x502ff9, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(HasCommon, 0x50300c, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(HasComponent, 0x43d950, bool, Params(const char* unk1), Args(unk1));
	DefineConstMethod(HasConversation, 0x435c4c, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(HasCorpse, 0x472fa3, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(HasDefend, 0x4a488b, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(HasFader, 0x50304d, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(HasFollower, 0x4c43a3, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(HasGold, 0x486209, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(HasGui, 0x468154, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(HasHire, 0x4cffe0, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(HasInventory, 0x442dd1, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(HasMagic, 0x486218, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(HasMind, 0x435c65, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(HasParent, 0x46802d, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(HasParty, 0x413477, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(HasPet, 0x413486, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(HasPhysics, 0x5030d4, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(HasPlacement, 0x4288f3, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(HasPotion, 0x503101, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(HasProxy, 0x503124, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(HasStash, 0x46dd5d, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(HasStore, 0x46dd76, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(HasZone, 0x50315b, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsActiveSpell, 0x7b1b65, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsActor, 0x7b1aa3, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsAllClients, 0x435c03, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsAmmo, 0x7b1aab, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsAnyHumanParty, 0x7b1abf, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsAnyHumanPartyMember, 0x7b1ad6, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsAnyHumanPartyMemberOrSummon, 0x7b1af0, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsArmor, 0x7b2b6d, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsAutoExpirationEnabled, 0x502f55, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsBreakable, 0x7b1b2d, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsChad, 0x7b4eb7, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsCommand, 0x7b4ed3, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsContainer, 0x7b1b44, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsDelayedMpDeletion, 0x502ed3, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsEnchanted, 0x502f34, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsEquipped, 0x7b2b83, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsFocused, 0x472f18, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsGlobalGo, 0x435bee, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsGold, 0x7b1b9b, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsHuded, 0x502f2b, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsInActiveScreenWorldFrustum, 0x7b2968, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsInActiveWorldFrustum, 0x7b2948, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsInAnyScreenWorldFrustum, 0x7b2928, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsInAnyWorldFrustum, 0x46805e, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsInFlick, 0x502f14, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsInHotGroup, 0x502ee9, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsInIntenseBattle, 0x502f3f, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsInsideInventory, 0x4680cb, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsInViewFrustum, 0x7b2b14, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsItem, 0x7b1bea, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsJames, 0x7b4f24, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsLocalGo, 0x502e9b, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsMarkedForDeletion, 0x502ec7, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsMarkedForPickup, 0x7b1c87, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsMeleeWeapon, 0x7b2b92, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsMouseShadowed, 0x502edf, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsNoStartupFx, 0x502f49, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsOmni, 0x413421, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsPackOnly, 0x7b1cb3, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsPlayerItemValid, 0x7b43ed, bool, Params(const Goid_* unk1), Args(unk1));
	DefineConstMethod(IsPlayerOnly, 0x49848c, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsPotion, 0x7b1bfc, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsProbed, 0x502f28, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsRangedWeapon, 0x7b2baf, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsScreenParty, 0x7b2bcd, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsScreenPartyMember, 0x7b2be6, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsScreenPlayerOwned, 0x7b2c09, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsSelectable, 0x7b1c05, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsSelected, 0x472f24, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsServerOnly, 0x435c0f, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsShield, 0x7b1c18, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsSingleton, 0x502ebc, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsSpawned, 0x7b1c2c, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsSpell, 0x7b1c3b, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsSpellBook, 0x7b1c59, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsTeamMember, 0x7b43a7, bool, Params(const Goid_* unk1), Args(unk1));
	DefineMethod(IsTeleporting, 0x435c1b, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsUsable, 0x7b1c70, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsVisibleInScreenWorldFrustum, 0x7b2998, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsWeapon, 0x7b1c9e, bool, NO_PARAMS, NO_ARGS);
	DefineMethod(Select, 0x472f30, bool, NO_PARAMS, NO_ARGS);
	DefineMethod(Select, 0x7b2a1f, bool, Params(bool unk1, bool unk2), Args(unk1, unk2));
	DefineMethod(SetComponentBool, 0x7b6bd4, bool, Params(const char* unk1, const char* unk2, bool unk3), Args(unk1, unk2, unk3));
	DefineMethod(SetComponentFloat, 0x7b6bed, bool, Params(const char* unk1, const char* unk2, float unk3), Args(unk1, unk2, unk3));
	DefineMethod(SetComponentGoid, 0x7b6c0a, bool, Params(const char* unk1, const char* unk2, const Goid_* unk3), Args(unk1, unk2, unk3));
	DefineMethod(SetComponentInt, 0x7b6bbb, bool, Params(const char* unk1, const char* unk2, int unk3), Args(unk1, unk2, unk3));
	DefineMethod(SetComponentScid, 0x7b6c23, bool, Params(const char* unk1, const char* unk2, const Scid_* unk3), Args(unk1, unk2, unk3));
	DefineMethod(SetComponentString, 0x7b7653, bool, Params(const char* unk1, const char* unk2, const gpbstring<char>& unk3), Args(unk1, unk2, unk3));
	DefineMethod(ToggleSelected, 0x502ef2, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(WasInViewFrustumRecently, 0x7b2b32, bool, Params(bool unk1), Args(unk1));
	DefineMethod(GetBestArmor, 0x7b1a94, Go*, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetOwningParty, 0x7b188a, Go*, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetParent, 0x409d08, Go*, NO_PARAMS, NO_ARGS);
	DefineMethod(GetRoot, 0x7b1869, Go*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryActor, 0x502fbe, GoActor*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryActor, 0x502fb9, GoActor*, Params(bool unk1), Args(unk1));
	DefineMethod(GetActor, 0x413450, GoActor*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryAspect, 0x502fc7, GoAspect*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryAspect, 0x502fc1, GoAspect*, Params(bool unk1), Args(unk1));
	DefineMethod(GetAspect, 0x413459, GoAspect*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryAttack, 0x502fd1, GoAttack*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryAttack, 0x502fcb, GoAttack*, Params(bool unk1), Args(unk1));
	DefineMethod(GetAttack, 0x44a6f0, GoAttack*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryBody, 0x502fdb, GoBody*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryBody, 0x502fd5, GoBody*, Params(bool unk1), Args(unk1));
	DefineMethod(GetBody, 0x472f86, GoBody*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryCoach, 0x502feb, GoCoach*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryCoach, 0x502fe5, GoCoach*, Params(bool unk1), Args(unk1));
	DefineMethod(GetCoach, 0x502ff5, GoCoach*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryCommon, 0x503008, GoCommon*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryCommon, 0x503002, GoCommon*, Params(bool unk1), Args(unk1));
	DefineMethod(GetCommon, 0x413463, GoCommon*, NO_PARAMS, NO_ARGS);
	DefineMethod(GetComponent, 0x46dd46, GoComponent*, Params(const char* unk1), Args(unk1));
	DefineMethod(QueryComponent, 0x7b50fb, GoComponent*, Params(const char* unk1, bool unk2), Args(unk1, unk2));
	DefineMethod(FUBI_RENAME_QueryConversation, 0x50301b, GoConversation*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryConversation, 0x503015, GoConversation*, Params(bool unk1), Args(unk1));
	DefineMethod(GetConversation, 0x435c48, GoConversation*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryCorpse, 0x503025, GoCorpse*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryCorpse, 0x50301f, GoCorpse*, Params(bool unk1), Args(unk1));
	DefineMethod(GetCorpse, 0x472f9f, GoCorpse*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryDefend, 0x50302f, GoDefend*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryDefend, 0x503029, GoDefend*, Params(bool unk1), Args(unk1));
	DefineMethod(GetDefend, 0x4a4887, GoDefend*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryFader, 0x50303f, GoFader*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryFader, 0x503039, GoFader*, Params(bool unk1), Args(unk1));
	DefineMethod(GetFader, 0x503049, GoFader*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryFollower, 0x50305c, GoFollower*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryFollower, 0x503056, GoFollower*, Params(bool unk1), Args(unk1));
	DefineMethod(GetFollower, 0x4c439f, GoFollower*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryGold, 0x50306c, GoGold*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryGold, 0x503066, GoGold*, Params(bool unk1), Args(unk1));
	DefineMethod(GetGold, 0x503070, GoGold*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryGui, 0x50307a, GoGui*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryGui, 0x503074, GoGui*, Params(bool unk1), Args(unk1));
	DefineMethod(GetGui, 0x472fb2, GoGui*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryHire, 0x503084, GoHire*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryHire, 0x50307e, GoHire*, Params(bool unk1), Args(unk1));
	DefineMethod(GetHire, 0x4cffdc, GoHire*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryInventory, 0x50308e, GoInventory*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryInventory, 0x503088, GoInventory*, Params(bool unk1), Args(unk1));
	DefineMethod(GetInventory, 0x442dcd, GoInventory*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryMagic, 0x503098, GoMagic*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryMagic, 0x503092, GoMagic*, Params(bool unk1), Args(unk1));
	DefineMethod(GetMagic, 0x468163, GoMagic*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryMind, 0x5030a2, GoMind*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryMind, 0x50309c, GoMind*, Params(bool unk1), Args(unk1));
	DefineMethod(GetMind, 0x435c61, GoMind*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryParty, 0x5030ac, GoParty*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryParty, 0x5030a6, GoParty*, Params(bool unk1), Args(unk1));
	DefineMethod(GetParty, 0x413473, GoParty*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryPet, 0x5030b6, GoPet*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryPet, 0x5030b0, GoPet*, Params(bool unk1), Args(unk1));
	DefineMethod(GetPet, 0x486227, GoPet*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryPhysics, 0x5030c6, GoPhysics*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryPhysics, 0x5030c0, GoPhysics*, Params(bool unk1), Args(unk1));
	DefineMethod(GetPhysics, 0x5030d0, GoPhysics*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryPlacement, 0x5030e3, GoPlacement*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryPlacement, 0x5030dd, GoPlacement*, Params(bool unk1), Args(unk1));
	DefineMethod(GetPlacement, 0x409da3, GoPlacement*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryPotion, 0x5030f3, GoPotion*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryPotion, 0x5030ed, GoPotion*, Params(bool unk1), Args(unk1));
	DefineMethod(GetPotion, 0x5030fd, GoPotion*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryProxy, 0x503116, GoProxy*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryProxy, 0x503110, GoProxy*, Params(bool unk1), Args(unk1));
	DefineMethod(GetProxy, 0x503120, GoProxy*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryStash, 0x503133, GoStash*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryStash, 0x50312d, GoStash*, Params(bool unk1), Args(unk1));
	DefineMethod(GetStash, 0x472fbc, GoStash*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryStore, 0x50313d, GoStore*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryStore, 0x503137, GoStore*, Params(bool unk1), Args(unk1));
	DefineMethod(GetStore, 0x46dd72, GoStore*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryZone, 0x50314d, GoZone*, NO_PARAMS, NO_ARGS);
	DefineMethod(FUBI_RENAME_QueryZone, 0x503147, GoZone*, Params(bool unk1), Args(unk1));
	DefineMethod(GetZone, 0x503157, GoZone*, NO_PARAMS, NO_ARGS);
	DefineMethod(GetComponentString, 0x7b7634, gpbstring<char>, Params(const char* unk1, const char* unk2, const gpbstring<char>& unk3), Args(unk1, unk2, unk3));
	DefineMethod(GetComponentString, 0x503ba4, gpbstring<char>, Params(const char* unk1, const char* unk2), Args(unk1, unk2));
	DefineMethod(GetMessage, 0x7b75a7, gpbstring<char>, Params(const char* unk1), Args(unk1));
	DefineConstMethod(GetTemplateDocs, 0x7b7471, gpbstring<char>, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetPlayer, 0x42852b, Player*, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetMaterial, 0x7b4397, const char*, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetTemplateName, 0x413419, const char*, NO_PARAMS, NO_ARGS);
	DefineConstMethod(DevGetFuelAddress, 0x502f2e, const gpbstring<char>&, NO_PARAMS, NO_ARGS);
	DefineConstMethod(CalcWorldFrustumMembership, 0x7b29d2, const FrustumId_*, Params(bool unk1), Args(unk1));
	DefineConstMethod(GetWorldFrustumMembership, 0x502eb5, const FrustumId_*, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetCloneSourceGoid, 0x502eae, const Goid_*, NO_PARAMS, NO_ARGS);
	DefineMethod(GetComponentGoid, 0x7b6b87, const Goid_*, Params(const char* unk1, const char* unk2, const Goid_* unk3), Args(unk1, unk2, unk3));
	DefineMethod(GetComponentGoid, 0x502fa1, const Goid_*, Params(const char* unk1, const char* unk2), Args(unk1, unk2));
	DefineConstMethod(GetGoid, 0x413406, const Goid_*, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetChildren, 0x413444, const GopColl&, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetForPlayerOnly, 0x49849e, const PlayerId_*, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetPlayerId, 0x7b191d, const PlayerId_*, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetRegionSource, 0x435bfc, const RegionId_*, NO_PARAMS, NO_ARGS);
	DefineMethod(GetComponentScid, 0x7b6ba1, const Scid_*, Params(const char* unk1, const char* unk2, const Scid_* unk3), Args(unk1, unk2, unk3));
	DefineMethod(GetComponentScid, 0x435c24, const Scid_*, Params(const char* unk1, const char* unk2), Args(unk1, unk2));
	DefineConstMethod(GetScid, 0x413415, const Scid_*, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetLifeState, 0x7b1a65, eLifeState, NO_PARAMS, NO_ARGS);
	DefineMethod(GetComponentFloat, 0x7b6b6d, float, Params(const char* unk1, const char* unk2, float unk3), Args(unk1, unk2, unk3));
	DefineMethod(GetComponentFloat, 0x472f44, float, Params(const char* unk1, const char* unk2), Args(unk1, unk2));
	DefineConstMethod(GetRadius, 0x7b1a73, float, NO_PARAMS, NO_ARGS);
	DefineMethod(GetComponentInt, 0x7b6b39, int, Params(const char* unk1, const char* unk2, int unk3), Args(unk1, unk2, unk3));
	DefineMethod(GetComponentInt, 0x502f79, int, Params(const char* unk1, const char* unk2), Args(unk1, unk2));
	DefineConstMethod(GetFlickRefCount, 0x502f0d, int, NO_PARAMS, NO_ARGS);
	DefineMethod(RCForcedExpiredTransfer, 0x7b6886, FuBi::Cookie__*, Params(Go* unk1), Args(unk1));
	DefineConstMethod(GetMachineId, 0x7b1927, unsigned long, NO_PARAMS, NO_ARGS);
	DefineMethod(PlayMaterialSound, 0x7b7144, unsigned long, Params(const char* unk1, const char* unk2, bool unk3), Args(unk1, unk2, unk3));
	DefineMethod(PlayMaterialSound, 0x7b7488, unsigned long, Params(const char* unk1, const Goid_* unk2, bool unk3), Args(unk1, unk2, unk3));
	DefineMethod(PlaySound, 0x7b64b9, unsigned long, Params(const char* unk1, bool unk2, GPGSound::eSampleType unk3), Args(unk1, unk2, unk3));
	DefineMethod(PlaySound, 0x7b661f, unsigned long, Params(const char* unk1, const Goid_* unk2, GPGSound::eSampleType unk3, float unk4, float unk5, bool unk6), Args(unk1, unk2, unk3, unk4, unk5, unk6));
	DefineMethod(PlaySound, 0x7b71c7, unsigned long, Params(const char* unk1, float unk2, float unk3), Args(unk1, unk2, unk3));
	DefineMethod(PlaySound, 0x7b6591, unsigned long, Params(const char* unk1, GPGSound::eSampleType unk2, float unk3, float unk4, bool unk5), Args(unk1, unk2, unk3, unk4, unk5));
	DefineMethod(PlayVoiceSound, 0x7b8379, unsigned long, Params(const char* unk1, bool unk2, bool unk3), Args(unk1, unk2, unk3));
	DefineMethod(PlayVoiceSound, 0x7b830e, unsigned long, Params(const char* unk1, bool unk2), Args(unk1, unk2));
	DefineMethod(PlayVoiceSound, 0x7b86b7, unsigned long, Params(const char* unk1, const Goid_* unk2, float unk3, float unk4, bool unk5), Args(unk1, unk2, unk3, unk4, unk5));
	DefineMethod(PlayVoiceSound, 0x7b862e, unsigned long, Params(const char* unk1, float unk2, float unk3, bool unk4), Args(unk1, unk2, unk3, unk4));
	DefineMethod(AddChild, 0x7b5a87, void, Params(Go* unk1), Args(unk1));
	DefineMethod(ClearParent, 0x502f71, void, NO_PARAMS, NO_ARGS);
	DefineMethod(DisableAutoExpiration, 0x502f69, void, NO_PARAMS, NO_ARGS);
	DefineMethod(EnableAutoExpiration, 0x502f61, void, NO_PARAMS, NO_ARGS);
	DefineMethod(EnableAutoExpiration, 0x7b2dfc, void, Params(bool unk1), Args(unk1));
	DefineMethod(PrepareToDrawNow, 0x502f20, void, NO_PARAMS, NO_ARGS);
	DefineMethod(PrepareToDrawNow, 0x7b1a51, void, Params(bool unk1), Args(unk1));
	DefineMethod(RCDeactivateTrigger, 0x7b3513, void, Params(unsigned short unk1), Args(unk1));
	DefineMethod(RCExplodeGo, 0x7b2f9f, void, Params(float unk1, const vector_3& unk2, unsigned long unk3), Args(unk1, unk2, unk3));
	DefineMethod(RCPlayCombatSoundPacker, 0x7b4fdc, void, Params(const_mem_ptr unk1), Args(unk1));
	DefineMethod(RCPlayMaterialSound, 0x7b74bc, void, Params(const char* unk1, const char* unk2, bool unk3), Args(unk1, unk2, unk3));
	DefineMethod(RCPlayMaterialSound, 0x7b7a79, void, Params(const char* unk1, const Goid_* unk2, bool unk3), Args(unk1, unk2, unk3));
	DefineMethod(RCPlayVoiceSound, 0x7b8c18, void, Params(unsigned long unk1, const char* unk2, bool unk3), Args(unk1, unk2, unk3));
	DefineMethod(RCPlayVoiceSoundIdPeek, 0x7b84d0, void, Params(eVoiceSound unk1, bool unk2), Args(unk1, unk2));
	DefineMethod(RCPlayVoiceSoundPeek, 0x7b83e4, void, Params(const char* unk1, bool unk2), Args(unk1, unk2));
	DefineMethod(RCRemoveAllEnchantmentsOnSelf, 0x7b3190, void, NO_PARAMS, NO_ARGS);
	DefineMethod(RCRemoveObjectEnchantmentsOnSelf, 0x7b32af, void, Params(unsigned long unk1), Args(unk1));
	DefineMethod(RCRpcSyncDataPeek, 0x7ba79e, void, Params(const_mem_ptr unk1), Args(unk1));
	DefineMethod(RCSend, 0x7b33fd, void, Params(WorldMessage& unk1, MESSAGE_DISPATCH_FLAG unk2), Args(unk1, unk2));
	DefineMethod(RCSetCollision, 0x7b309b, void, Params(const Goid_* unk1, bool unk2), Args(unk1, unk2));
	DefineMethod(RCSetForPlayerOnly, 0x7b3920, void, Params(const PlayerId_* unk1), Args(unk1));
	DefineMethod(RCSetParent, 0x7b67a1, void, Params(Go* unk1), Args(unk1));
	DefineMethod(RCSetPlayer, 0x7b41dd, void, Params(const PlayerId_* unk1), Args(unk1));
	DefineMethod(RemoveAllChildren, 0x7b5bac, void, NO_PARAMS, NO_ARGS);
	DefineMethod(RemoveChild, 0x7b4670, void, Params(Go* unk1), Args(unk1));
	DefineMethod(SetModifiersDirty, 0x7b1ccc, void, Params(bool unk1), Args(unk1));
	DefineMethod(SetParent, 0x7b5bf6, void, Params(Go* unk1), Args(unk1));
	DefineMethod(SPlayMaterialSound, 0x7b7b64, void, Params(const char* unk1, const char* unk2, bool unk3), Args(unk1, unk2, unk3));
	DefineMethod(SPlayMaterialSound, 0x7b8746, void, Params(const char* unk1, const Goid_* unk2, bool unk3), Args(unk1, unk2, unk3));
	DefineMethod(SPlayVoiceSound, 0x7b9350, void, Params(const char* unk1, bool unk2), Args(unk1, unk2));
	DefineMethod(SPlayVoiceSound, 0x7b9370, void, Params(unsigned long unk1, const char* unk2, bool unk3), Args(unk1, unk2, unk3));
	DefineMethod(SRemoveObjectEnchantmentsOnSelf, 0x7b46c2, void, Params(const Goid_* unk1), Args(unk1));
	DefineMethod(SSetForPlayerOnly, 0x7b478c, void, Params(const PlayerId_* unk1), Args(unk1));
	DefineMethod(SSetParent, 0x7b71e9, void, Params(Go* unk1), Args(unk1));
	DefineMethod(SSetPlayer, 0x7b4e52, void, Params(const PlayerId_* unk1), Args(unk1));
	DefineMethod(StopSound, 0x7b2e83, void, Params(unsigned long unk1), Args(unk1));
};

// Only referenced by Go;
class GoFader {
public:
};
