#pragma once

#include "FuBi.h"

class GoInventory {
public:
	DefineStaticMethod(FUBI_NetToInstance, 0x408daf, GoInventory*, Params(unsigned long unk1, FuBi::Cookie__** unk2), Args(unsigned long unk1, FuBi::Cookie__** unk2));
	/*GoInventory*/ private: /*static*/ unsigned long /*__cdecl*/ FUBI_InstanceToNet(GoInventory* unk1); //0x00408da6
	DefineMethod(RCAdd, 0x831c07, FuBi::Cookie__*, Params(Go* unk1, eInventoryLocation unk2, eActionOrigin unk3, bool unk4), Args(Go* unk1, eInventoryLocation unk2, eActionOrigin unk3, bool unk4));
	DefineMethod(RCAddGold, 0x408cf5, FuBi::Cookie__*, Params(int unk1), Args(int unk1));
	DefineMethod(RCAutoEquip, 0x8342b5, FuBi::Cookie__*, Params(eEquipSlot unk1, const Goid_* unk2, eActionOrigin unk3, bool unk4), Args(eEquipSlot unk1, const Goid_* unk2, eActionOrigin unk3, bool unk4));
	DefineMethod(RCEquip, 0x834146, FuBi::Cookie__*, Params(eEquipSlot unk1, const Goid_* unk2, eActionOrigin unk3), Args(eEquipSlot unk1, const Goid_* unk2, eActionOrigin unk3));
	DefineMethod(RCRemove, 0x82de8c, FuBi::Cookie__*, Params(Go* unk1, const SiegePos& unk2, const Quat& unk3, bool unk4), Args(Go* unk1, const SiegePos& unk2, const Quat& unk3, bool unk4));
	DefineMethod(RCRemove, 0x82dfe6, FuBi::Cookie__*, Params(Go* unk1, const SiegePos& unk2), Args(Go* unk1, const SiegePos& unk2));
	DefineMethod(RCRemove, 0x82e141, FuBi::Cookie__*, Params(Go* unk1), Args(Go* unk1));
	DefineMethod(RCSelect, 0x829cf0, FuBi::Cookie__*, Params(eInventoryLocation unk1, eActionOrigin unk2), Args(eInventoryLocation unk1, eActionOrigin unk2));
	DefineMethod(RCSetGold, 0x829e34, FuBi::Cookie__*, Params(int unk1), Args(int unk1));
	DefineMethod(RCSetLocation, 0x8314e8, FuBi::Cookie__*, Params(Go* unk1, eInventoryLocation unk2, bool unk3), Args(Go* unk1, eInventoryLocation unk2, bool unk3));
	DefineMethod(RCTransfer, 0x831e11, FuBi::Cookie__*, Params(Go* unk1, Go* unk2, eInventoryLocation unk3, eActionOrigin unk4, bool unk5), Args(Go* unk1, Go* unk2, eInventoryLocation unk3, eActionOrigin unk4, bool unk5));
	DefineMethod(RCUnequip, 0x408c87, FuBi::Cookie__*, Params(eEquipSlot unk1, eActionOrigin unk2), Args(eEquipSlot unk1, eActionOrigin unk2));
	DefineMethod(RCDeactivateGuiItems, 0x82f6b1, void, Params(), Args());
	DefineMethod(RCSetLocationPreference, 0x8276d6, void, Params(eInventoryLocation unk1), Args(eInventoryLocation unk1));
	DefineMethod(SDeactivateGuiItems, 0x830123, void, Params(), Args());
	DefineConstMethod(CanAdd, 0x83005d, bool, Params(const Go* unk1, eInventoryLocation unk2, bool unk3), Args(const Go* unk1, eInventoryLocation unk2, bool unk3));
	DefineMethod(CanGive, 0x830242, bool, Params(const Goid_* unk1, const Goid_* unk2, eActionOrigin unk3), Args(const Goid_* unk1, const Goid_* unk2, eActionOrigin unk3));
	DefineConstMethod(Contains, 0x829c57, bool, Params(const Go* unk1), Args(const Go* unk1));
	DefineMethod(GetCanManipulateInventory, 0x408c68, bool, Params(), Args());
	DefineMethod(GetForceGet, 0x408d3a, bool, Params(), Args());
	DefineMethod(GetMarkAllInventoryForRemoval, 0x408cca, bool, Params(), Args());
	DefineConstMethod(HasGold, 0x408ce9, bool, Params(), Args());
	DefineConstMethod(HasGridbox, 0x408d48, bool, Params(), Args());
	DefineConstMethod(HasItems, 0x828fdf, bool, Params(eInventoryLocation unk1, bool unk2), Args(eInventoryLocation unk1, bool unk2));
	DefineConstMethod(HasSelectedOffensiveWeaponOrSpell, 0x408d17, bool, Params(), Args());
	DefineMethod(IsActiveSpell, 0x829c20, bool, Params(const Go* unk1), Args(const Go* unk1));
	DefineConstMethod(IsAnyWeaponEquipped, 0x408b89, bool, Params(), Args());
	DefineConstMethod(IsEitherHandEquipped, 0x408ba9, bool, Params(), Args());
	DefineConstMethod(IsEquipped, 0x408b5b, bool, Params(const Go* unk1), Args(const Go* unk1));
	DefineMethod(IsItemSetActive, 0x830f48, bool, Params(const gpbstring<char>& unk1), Args(const gpbstring<char>& unk1));
	DefineConstMethod(IsMeleeWeaponEquipped, 0x826415, bool, Params(), Args());
	DefineConstMethod(IsMeleeWeaponSelected, 0x826821, bool, Params(), Args());
	DefineConstMethod(IsPackOnly, 0x408b57, bool, Params(), Args());
	DefineConstMethod(IsRangedWeaponEquipped, 0x826454, bool, Params(), Args());
	DefineConstMethod(IsRangedWeaponSelected, 0x82683c, bool, Params(), Args());
	DefineConstMethod(IsSlotEquipped, 0x408b74, bool, Params(eEquipSlot unk1), Args(eEquipSlot unk1));
	DefineConstMethod(IsSpellInProgress, 0x82961c, bool, Params(const gpbstring<char>& unk1), Args(const gpbstring<char>& unk1));
	DefineConstMethod(IsSpellSelected, 0x826894, bool, Params(), Args());
	DefineConstMethod(ListItems, 0x82b625, bool, Params(eInventoryLocation unk1, GopColl& unk2, bool unk3, bool unk4), Args(eInventoryLocation unk1, GopColl& unk2, bool unk3, bool unk4));
	DefineConstMethod(ListItems, 0x408c1d, bool, Params(eInventoryLocation unk1, GopColl& unk2, bool unk3), Args(eInventoryLocation unk1, GopColl& unk2, bool unk3));
	DefineConstMethod(ListItems, 0x40a3be, bool, Params(eInventoryLocation unk1, GopColl& unk2), Args(eInventoryLocation unk1, GopColl& unk2));
	DefineConstMethod(ListItems, 0x82be6d, bool, Params(eQueryTrait unk1, eInventoryLocation unk2, GopColl& unk3, bool unk4, bool unk5), Args(eQueryTrait unk1, eInventoryLocation unk2, GopColl& unk3, bool unk4, bool unk5));
	DefineConstMethod(ListItems, 0x408c34, bool, Params(eQueryTrait unk1, eInventoryLocation unk2, GopColl& unk3, bool unk4), Args(eQueryTrait unk1, eInventoryLocation unk2, GopColl& unk3, bool unk4));
	DefineConstMethod(ListItems, 0x40a3d4, bool, Params(eQueryTrait unk1, eInventoryLocation unk2, GopColl& unk3), Args(eQueryTrait unk1, eInventoryLocation unk2, GopColl& unk3));
	DefineConstMethod(ListItems, 0x82b646, bool, Params(QtColl& unk1, eInventoryLocation unk2, GopColl& unk3, bool unk4, bool unk5), Args(QtColl& unk1, eInventoryLocation unk2, GopColl& unk3, bool unk4, bool unk5));
	DefineConstMethod(ListItems, 0x408c4e, bool, Params(QtColl& unk1, eInventoryLocation unk2, GopColl& unk3, bool unk4), Args(QtColl& unk1, eInventoryLocation unk2, GopColl& unk3, bool unk4));
	DefineConstMethod(ListItems, 0x40a3ed, bool, Params(QtColl& unk1, eInventoryLocation unk2, GopColl& unk3), Args(QtColl& unk1, eInventoryLocation unk2, GopColl& unk3));
	DefineConstMethod(ListVisibleItems, 0x829cb9, bool, Params(GopColl& unk1), Args(GopColl& unk1));
	DefineMethod(LocationContainsTemplate, 0x82ccdd, bool, Params(eInventoryLocation unk1, const gpbstring<char>& unk2), Args(eInventoryLocation unk1, const gpbstring<char>& unk2));
	DefineMethod(SAutoGet, 0x8380d5, bool, Params(const Goid_* unk1, eActionOrigin unk2), Args(const Goid_* unk1, eActionOrigin unk2));
	DefineMethod(SAutoGive, 0x837ad7, bool, Params(const Goid_* unk1, const Goid_* unk2, eActionOrigin unk3), Args(const Goid_* unk1, const Goid_* unk2, eActionOrigin unk3));
	DefineMethod(SAutoUse, 0x82e298, bool, Params(const Goid_* unk1, eActionOrigin unk2, bool unk3), Args(const Goid_* unk1, eActionOrigin unk2, bool unk3));
	DefineMethod(SBeginGive, 0x82865b, bool, Params(const Goid_* unk1, eActionOrigin unk2), Args(const Goid_* unk1, eActionOrigin unk2));
	DefineMethod(SEndGive, 0x832a9a, bool, Params(const Goid_* unk1, const Goid_* unk2, eActionOrigin unk3), Args(const Goid_* unk1, const Goid_* unk2, eActionOrigin unk3));
	DefineConstMethod(TestEquip, 0x833af0, bool, Params(const Goid_* unk1, eEquipSlot unk2), Args(const Goid_* unk1, eEquipSlot unk2));
	DefineConstMethod(TestEquipPassive, 0x832fe2, bool, Params(const Goid_* unk1), Args(const Goid_* unk1));
	DefineConstMethod(TestGet, 0x8330ef, bool, Params(const Goid_* unk1, bool unk2), Args(const Goid_* unk1, bool unk2));
	DefineConstMethod(TestGet, 0x408cd1, bool, Params(const Goid_* unk1), Args(const Goid_* unk1));
	DefineConstMethod(GetActiveMeleeWeapon, 0x82968b, Go*, Params(), Args());
	DefineConstMethod(GetActiveRangedWeapon, 0x8296d8, Go*, Params(), Args());
	DefineConstMethod(GetActiveSpellBook, 0x408d9f, Go*, Params(), Args());
	DefineConstMethod(GetBestArmor, 0x826974, Go*, Params(), Args());
	DefineConstMethod(GetEquipped, 0x828edb, Go*, Params(const gpbstring<char>& unk1), Args(const gpbstring<char>& unk1));
	DefineConstMethod(GetEquipped, 0x8263be, Go*, Params(eEquipSlot unk1), Args(eEquipSlot unk1));
	DefineConstMethod(GetEquippedMeleeWeapon, 0x8263cc, Go*, Params(), Args());
	DefineConstMethod(GetEquippedRangedWeapon, 0x826421, Go*, Params(), Args());
	DefineConstMethod(GetItem, 0x828f23, Go*, Params(eInventoryLocation unk1), Args(eInventoryLocation unk1));
	DefineConstMethod(GetItemFromTemplate, 0x828f8b, Go*, Params(const gpbstring<char>& unk1), Args(const gpbstring<char>& unk1));
	DefineMethod(GetItemFromTemplate, 0x82cd5c, Go*, Params(eInventoryLocation unk1, const gpbstring<char>& unk2), Args(eInventoryLocation unk1, const gpbstring<char>& unk2));
	DefineConstMethod(GetSelectedDualWieldWeapon, 0x82a5b0, Go*, Params(), Args());
	DefineConstMethod(GetSelectedItem, 0x408bcb, Go*, Params(), Args());
	DefineConstMethod(GetSelectedMeleeWeapon, 0x8267ee, Go*, Params(), Args());
	DefineConstMethod(GetSelectedOffensiveWeaponOrSpell, 0x8278e7, Go*, Params(), Args());
	DefineConstMethod(GetSelectedRangedWeapon, 0x826807, Go*, Params(), Args());
	DefineConstMethod(GetSelectedSpell, 0x826858, Go*, Params(), Args());
	DefineConstMethod(GetSelectedWeapon, 0x8267d2, Go*, Params(), Args());
	DefineConstMethod(GetSelectedWeaponOrSpell, 0x8278ab, Go*, Params(), Args());
	DefineConstMethod(GetShield, 0x82695b, Go*, Params(), Args());
	DefineConstMethod(GetGridbox, 0x408d41, UIGridbox*, Params(), Args());
	DefineMethod(GetAnimStance, 0x827687, eAnimStance, Params(), Args());
	DefineConstMethod(GetEquippedSlot, 0x8276a0, eEquipSlot, Params(const Go* unk1), Args(const Go* unk1));
	DefineConstMethod(GetEquippedSlot, 0x828426, eEquipSlot, Params(const Goid_* unk1), Args(const Goid_* unk1));
	DefineConstMethod(GetLocation, 0x829c85, eInventoryLocation, Params(const Go* unk1), Args(const Go* unk1));
	DefineConstMethod(GetSelectedLocation, 0x408c16, eInventoryLocation, Params(), Args());
	DefineConstMethod(GetFullRatio, 0x82977e, float, Params(), Args());
	DefineMethod(GetAnimStanceInt, 0x408b52, int, Params(), Args());
	DefineConstMethod(GetGold, 0x408ce2, int, Params(), Args());
	DefineConstMethod(GetGridAreaFree, 0x408d74, int, Params(), Args());
	DefineConstMethod(GetGridAreaMax, 0x408d6c, int, Params(), Args());
	DefineConstMethod(GetGridAreaUsed, 0x829725, int, Params(), Args());
	DefineConstMethod(GetGridHeight, 0x408d68, int, Params(), Args());
	DefineConstMethod(GetGridWidth, 0x408d64, int, Params(), Args());
	DefineMethod(GetNumActiveSpells, 0x408d23, int, Params(), Args());
	DefineMethod(GetNumSetBonuses, 0x830b40, int, Params(const gpbstring<char>& unk1), Args(const gpbstring<char>& unk1));
	DefineMethod(RSAdd, 0x831fbb, FuBi::Cookie__*, Params(Go* unk1, eInventoryLocation unk2, eActionOrigin unk3, bool unk4), Args(Go* unk1, eInventoryLocation unk2, eActionOrigin unk3, bool unk4));
	DefineMethod(RSAutoEquip, 0x8374df, FuBi::Cookie__*, Params(eEquipSlot unk1, const Goid_* unk2, eActionOrigin unk3, bool unk4), Args(eEquipSlot unk1, const Goid_* unk2, eActionOrigin unk3, bool unk4));
	DefineMethod(RSAutoEquip, 0x408c9f, FuBi::Cookie__*, Params(eEquipSlot unk1, const Goid_* unk2, eActionOrigin unk3), Args(eEquipSlot unk1, const Goid_* unk2, eActionOrigin unk3));
	DefineMethod(RSCreateAddItem, 0x8316b5, FuBi::Cookie__*, Params(eInventoryLocation unk1, const gpbstring<char>& unk2), Args(eInventoryLocation unk1, const gpbstring<char>& unk2));
	DefineMethod(RSEquip, 0x837361, FuBi::Cookie__*, Params(eEquipSlot unk1, const Goid_* unk2, eActionOrigin unk3), Args(eEquipSlot unk1, const Goid_* unk2, eActionOrigin unk3));
	DefineMethod(RSRemove, 0x82ea69, FuBi::Cookie__*, Params(Go* unk1, bool unk2, Go* unk3), Args(Go* unk1, bool unk2, Go* unk3));
	DefineMethod(RSRemove, 0x408cb6, FuBi::Cookie__*, Params(Go* unk1, bool unk2), Args(Go* unk1, bool unk2));
	DefineMethod(RSSelect, 0x82b6a3, FuBi::Cookie__*, Params(eInventoryLocation unk1, eActionOrigin unk2), Args(eInventoryLocation unk1, eActionOrigin unk2));
	DefineMethod(RSSetLocation, 0x831d11, FuBi::Cookie__*, Params(Go* unk1, eInventoryLocation unk2, bool unk3), Args(Go* unk1, eInventoryLocation unk2, bool unk3));
	DefineMethod(RSTransfer, 0x832135, FuBi::Cookie__*, Params(Go* unk1, Go* unk2, eInventoryLocation unk3, eActionOrigin unk4, bool unk5), Args(Go* unk1, Go* unk2, eInventoryLocation unk3, eActionOrigin unk4, bool unk5));
	DefineMethod(RSUnequip, 0x408c6f, FuBi::Cookie__*, Params(eEquipSlot unk1, eActionOrigin unk2), Args(eEquipSlot unk1, eActionOrigin unk2));
	DefineMethod(AddDelayedPcontent, 0x837a87, void, Params(), Args());
	DefineMethod(DropItemsAroundBody, 0x408d0b, void, Params(), Args());
	DefineMethod(DropItemsFor, 0x8375e2, void, Params(const Goid_* unk1), Args(const Goid_* unk1));
	DefineMethod(RCBeginGive, 0x827915, void, Params(const Goid_* unk1, unsigned long unk2), Args(const Goid_* unk1, unsigned long unk2));
	DefineMethod(RCBeginUse, 0x826588, void, Params(), Args());
	DefineMethod(RCEndGive, 0x8322c3, void, Params(const Goid_* unk1, const Goid_* unk2, eActionOrigin unk3, unsigned long unk4), Args(const Goid_* unk1, const Goid_* unk2, eActionOrigin unk3, unsigned long unk4));
	DefineMethod(RCEndUse, 0x826695, void, Params(), Args());
	DefineMethod(RCRefreshMagicalEquipment, 0x82946e, void, Params(), Args());
	DefineMethod(RCReleaseGridboxes, 0x82c019, void, Params(unsigned long unk1), Args(unsigned long unk1));
	DefineMethod(RCRemoveExpendedItem, 0x82cfcc, void, Params(const Goid_* unk1), Args(const Goid_* unk1));
	DefineMethod(RCSetCanManipulateInventory, 0x82bebc, void, Params(bool unk1, unsigned long unk2), Args(bool unk1, unsigned long unk2));
	DefineMethod(RCSetCustomHead, 0x82d24b, void, Params(const gpbstring<char>& unk1), Args(const gpbstring<char>& unk1));
	DefineMethod(RCSetForceGet, 0x82698c, void, Params(bool unk1), Args(bool unk1));
	DefineMethod(RCSetInventoryDirty, 0x827b76, void, Params(bool unk1), Args(bool unk1));
	DefineMethod(ReportItemSwitching, 0x827c70, void, Params(Go* unk1), Args(Go* unk1));
	DefineMethod(RSReleaseGridboxes, 0x82d330, void, Params(), Args());
	DefineMethod(RSSetForceGet, 0x827a36, void, Params(bool unk1), Args(bool unk1));
	DefineMethod(RSSetLocationPreference, 0x828570, void, Params(eInventoryLocation unk1), Args(eInventoryLocation unk1));
	DefineMethod(RSSetMarkAllInventoryForRemoval, 0x82649c, void, Params(bool unk1), Args(bool unk1));
	DefineMethod(RSTicketCreateItemForShopkeep, 0x83259b, void, Params(const gpbstring<char>& unk1), Args(const gpbstring<char>& unk1));
	DefineMethod(RSUsePotion, 0x82e50a, void, Params(const Goid_* unk1, eActionOrigin unk2), Args(const Goid_* unk1, eActionOrigin unk2));
	DefineMethod(SBeginUse, 0x8277bb, void, Params(const Goid_* unk1), Args(const Goid_* unk1));
	DefineMethod(SEndUse, 0x8277f4, void, Params(const Goid_* unk1), Args(const Goid_* unk1));
	DefineMethod(SetGridbox, 0x408d54, void, Params(UIGridbox* unk1), Args(UIGridbox* unk1));
	DefineMethod(SetLocationPreference, 0x826460, void, Params(eInventoryLocation unk1), Args(eInventoryLocation unk1));
	DefineMethod(SetNumActiveSpells, 0x408d2a, void, Params(int unk1), Args(int unk1));
	DefineMethod(SRefreshMagicalEquipment, 0x82a5ab, void, Params(), Args());
	DefineMethod(SSetCanManipulateInventory, 0x82cddb, void, Params(bool unk1), Args(bool unk1));
	DefineMethod(SSetCustomHead, 0x82e688, void, Params(const gpbstring<char>& unk1), Args(const gpbstring<char>& unk1));
	DefineMethod(SSetGold, 0x82b81b, void, Params(int unk1), Args(int unk1));
	DefineMethod(SSetInventoryDirty, 0x828696, void, Params(bool unk1), Args(bool unk1));
	DefineMethod(SSyncRevivedPartyGold, 0x82ba1e, void, Params(), Args());
};
