#pragma once

#include "Enums.h"
#include "FuBi.h"
#include "Job.h"
#include "JobAttributeBits.h"
#include "JobReq.h"

#include "ClassMacros.h"

struct SiegePos;

enum eActorDisposition {

};

enum eCombatOrders {

};

enum eFocusOrders {

};
	
enum eMovementOrders {

};

enum eWeaponPreference {

};

class GoMind {
public:
	DefineStaticMethod(FUBI_NetToInstance, 0x412564, GoMind*, Params(unsigned long unk1, FuBi::Cookie__** unk2), Args(unk1, unk2));
	DefineStaticMethod(FUBI_InstanceToNet, 0x41255b, unsigned long, Params(GoMind* unk1), Args(unk1));
	DefineMethod(GetBrainActive, 0x41252e, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsInUpdateScope, 0x412536, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsVisible, 0x86da52, bool, Params(const Goid_* unk1), Args(unk1));
	DefineMethod(JobRecentlyFailedToPathTo, 0x86a3ba, bool, Params(Go* unk1), Args(unk1));
	DefineMethod(GetHandlingMessage, 0x41250d, WorldMessage*, NO_PARAMS, NO_ARGS);
	DefineMethod(GetInitialCommand, 0x41252a, const Scid_*, NO_PARAMS, NO_ARGS);
	DefineMethod(GetTempGopColl1, 0x41253f, GopColl&, NO_PARAMS, NO_ARGS);
	DefineMethod(GetTempGopColl2, 0x412546, GopColl&, NO_PARAMS, NO_ARGS);
	DefineMethod(GetTempGopColl3, 0x41254d, GopColl&, NO_PARAMS, NO_ARGS);
	DefineMethod(GetTempQtColl1, 0x412554, QtColl&, NO_PARAMS, NO_ARGS);
	DefineMethod(ReqResetSensorsSelfAndVisible, 0x86f9b6, void, NO_PARAMS, NO_ARGS);
	DefineMethod(RequestProcessHitEngaged, 0x412511, void, NO_PARAMS, NO_ARGS);
	DefineMethod(ResetSensors, 0x86c67e, void, NO_PARAMS, NO_ARGS);
	DefineMethod(SetInitialCommand, 0x412519, void, Params(const Scid_* unk1), Args(unk1));
	DefineConstMethod(ActorAutoDefendsOthers, 0x41240e, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(ActorAutoHealsOthersLife, 0x412418, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(ActorAutoHealsSelfLife, 0x412421, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(ActorAutoHealsSelfMana, 0x41242c, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(ActorAutoSwitchesToMagic, 0x412483, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(ActorAutoSwitchesToMelee, 0x41246f, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(ActorAutoSwitchesToRanged, 0x412478, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(ActorPrefersMagic, 0x412452, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(ActorPrefersMelee, 0x412438, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(ActorPrefersRanged, 0x412445, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(AmAttacking, 0x86ba44, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(AmBusy, 0x411b27, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(AmFacing, 0x86c20f, bool, Params(Go* unk1), Args(unk1));
	DefineConstMethod(AmFacing, 0x86acc9, bool, Params(const SiegePos& unk1), Args(unk1));
	DefineConstMethod(AmGuarding, 0x8687d8, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(AmPatrolling, 0x869d55, bool, NO_PARAMS, NO_ARGS);
	DefineMethod(AreAliveEnemiesVisible, 0x86aabd, bool, NO_PARAMS, NO_ARGS);
	DefineMethod(AreAliveFriendsVisible, 0x86ab28, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(AreItemsVisible, 0x86acb6, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(CanOperateOn, 0x8687ea, bool, Params(Go* unk1, bool unk2), Args(unk1, unk2));
	DefineMethod(CanOperateOn, 0x411b2f, bool, Params(Go* unk1), Args(unk1));
	DefineMethod(DoingJobOriginatingFrom, 0x86bc37, bool, Params(eJobQ unk1, Go* unk2), Args(unk1, unk2));
	DefineMethod(GetActorAutoFidgets, 0x412369, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetAutoItems, 0x86f225, bool, Params(eQueryTrait unk1, GopColl& unk2), Args(unk1, unk2));
	DefineConstMethod(GetAutoItems, 0x870502, bool, Params(GopColl& unk1), Args(unk1));
	DefineConstMethod(GetAutoItems, 0x86b25b, bool, Params(QtColl& unk1, GopColl& unk2), Args(unk1, unk2));
	DefineConstMethod(GetCanJump, 0x4122d3, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetClosestVisible, 0x870476, bool, Params(eQueryTrait unk1, GopColl& unk2), Args(unk1, unk2));
	DefineConstMethod(GetClosestVisible, 0x86e38a, bool, Params(float unk1, QtColl& unk2, GopColl& unk3), Args(unk1, unk2, unk3));
	DefineConstMethod(GetClosestVisible, 0x411dd2, bool, Params(QtColl& unk1, GopColl& unk2), Args(unk1, unk2));
	DefineMethod(GetClosestVisibleEnemies, 0x86e58e, bool, Params(float unk1, GopColl& unk2), Args(unk1, unk2));
	DefineMethod(GetClosestVisibleEnemies, 0x411e52, bool, Params(GopColl& unk1), Args(unk1));
	DefineMethod(GetClosestVisibleFriends, 0x86e609, bool, Params(float unk1, GopColl& unk2), Args(unk1, unk2));
	DefineMethod(GetClosestVisibleFriends, 0x411e6b, bool, Params(GopColl& unk1), Args(unk1));
	DefineConstMethod(GetEnemiesAndSummonsInSphere, 0x86ff5a, bool, Params(float unk1, GopColl& unk2), Args(unk1, unk2));
	DefineConstMethod(GetEnemiesInSphere, 0x86fed4, bool, Params(float unk1, GopColl& unk2), Args(unk1, unk2));
	DefineConstMethod(GetEngagedMe, 0x86f124, bool, Params(GopColl& unk1), Args(unk1));
	DefineConstMethod(GetEngagedMeEnemies, 0x86f199, bool, Params(GopColl& unk1), Args(unk1));
	DefineConstMethod(GetFarthestVisible, 0x8704bc, bool, Params(eQueryTrait unk1, GopColl& unk2), Args(unk1, unk2));
	DefineConstMethod(GetFarthestVisible, 0x86e65e, bool, Params(QtColl& unk1, GopColl& unk2), Args(unk1, unk2));
	DefineConstMethod(GetFriendsAndSummonsInSphere, 0x87000e, bool, Params(float unk1, GopColl& unk2), Args(unk1, unk2));
	DefineConstMethod(GetFriendsInSphere, 0x86ff88, bool, Params(float unk1, GopColl& unk2), Args(unk1, unk2));
	DefineConstMethod(GetItemsInSphere, 0x86fd67, bool, Params(float unk1, GopColl& unk2), Args(unk1, unk2));
	DefineConstMethod(GetLeashTeleportToHome, 0x86c645, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetMayAttack, 0x4123de, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetMayAttackHeroes, 0x4123ea, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetMayBeAttacked, 0x4123f6, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetMayBeAttackedByHeroes, 0x412402, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetMayProcessAI, 0x412394, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetMayProcessSensors, 0x4123b8, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetOccupantsInSphere, 0x86fded, bool, Params(float unk1, GopColl& unk2), Args(unk1, unk2));
	DefineConstMethod(GetPartyMembersAndSummonsInSphere, 0x86aa8f, bool, Params(float unk1, GopColl* unk2), Args(unk1, unk2));
	DefineConstMethod(GetPartyMembersInSphere, 0x86aa2e, bool, Params(float unk1, GopColl* unk2), Args(unk1, unk2));
	DefineConstMethod(GetVisible, 0x870058, bool, Params(eQueryTrait unk1, GopColl& unk2, float unk3), Args(unk1, unk2, unk3));
	DefineConstMethod(GetVisible, 0x411c7b, bool, Params(eQueryTrait unk1, GopColl& unk2), Args(unk1, unk2));
	DefineConstMethod(GetVisible, 0x86dd66, bool, Params(QtColl& unk1, GoidColl& unk2, float unk3), Args(unk1, unk2, unk3));
	DefineConstMethod(GetVisible, 0x87003c, bool, Params(QtColl& unk1, GoidColl& unk2), Args(unk1, unk2));
	DefineConstMethod(GetVisible, 0x86de0e, bool, Params(QtColl& unk1, GopColl& unk2, float unk3), Args(unk1, unk2, unk3));
	DefineConstMethod(GetVisible, 0x411c97, bool, Params(QtColl& unk1, GopColl& unk2), Args(unk1, unk2));
	DefineConstMethod(GetVisibleAtPosition, 0x86def7, bool, Params(const SiegePos& unk1, QtColl& unk2, GopColl& unk3, float unk4), Args(unk1, unk2, unk3, unk4));
	DefineConstMethod(GetVisibleCastTargets, 0x870122, bool, Params(GopColl& unk1, Go* unk2, bool unk3, float unk4, unsigned long unk5), Args(unk1, unk2, unk3, unk4, unk5));
	DefineConstMethod(GetVisibleCastTargets, 0x411d99, bool, Params(GopColl& unk1, Go* unk2, bool unk3, float unk4), Args(unk1, unk2, unk3, unk4));
	DefineConstMethod(GetVisibleCastTargets, 0x411d7c, bool, Params(GopColl& unk1, Go* unk2, bool unk3), Args(unk1, unk2, unk3));
	DefineConstMethod(GetVisibleEnemies, 0x86e025, bool, Params(GopColl& unk1, float unk2), Args(unk1, unk2));
	DefineConstMethod(GetVisibleEnemies, 0x411d18, bool, Params(GopColl& unk1), Args(unk1));
	DefineConstMethod(GetVisibleFriends, 0x86e0a0, bool, Params(GopColl& unk1, float unk2), Args(unk1, unk2));
	DefineConstMethod(GetVisibleFriends, 0x411d31, bool, Params(GopColl& unk1), Args(unk1));
	DefineConstMethod(GetVisibleFriendsForPlay, 0x8700a5, bool, Params(GopColl& unk1, const char* unk2), Args(unk1, unk2));
	DefineConstMethod(GetVisibleItems, 0x86e0f5, bool, Params(GopColl& unk1, float unk2), Args(unk1, unk2));
	DefineConstMethod(GetVisibleItems, 0x411d4a, bool, Params(GopColl& unk1), Args(unk1));
	DefineConstMethod(GetVisibleItemsToLoot, 0x86e14a, bool, Params(GopColl& unk1, float unk2), Args(unk1, unk2));
	DefineConstMethod(GetVisibleItemsToLoot, 0x411d63, bool, Params(GopColl& unk1), Args(unk1));
	DefineConstMethod(HasActionJatInQueue, 0x411b06, bool, Params(eJobAbstractType unk1), Args(unk1));
	DefineConstMethod(HasBrainJatInQueue, 0x411af5, bool, Params(eJobAbstractType unk1), Args(unk1));
	DefineMethod(InitBrain, 0x8718c8, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsActorMovingAway, 0x86a42d, bool, Params(Go* unk1), Args(unk1));
	DefineConstMethod(IsAngry, 0x411c5b, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsEnemy, 0x868a7c, bool, Params(const Go* unk1), Args(unk1));
	DefineConstMethod(IsFleeingFromMe, 0x86f028, bool, Params(const Goid_* unk1), Args(unk1));
	DefineConstMethod(IsFlickCaptured, 0x411b40, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsFriend, 0x868ad9, bool, Params(const Go* unk1), Args(unk1));
	DefineMethod(IsFrontActionHumanInterruptable, 0x86a03e, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsGuardingTarget, 0x411b7a, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsInEngageRange, 0x86bfed, bool, Params(Go* unk1, Go* unk2), Args(unk1, unk2));
	DefineConstMethod(IsInEngageRange, 0x86bfcf, bool, Params(Go* unk1), Args(unk1));
	DefineConstMethod(IsInJumpRange, 0x86bf69, bool, Params(Go* unk1), Args(unk1));
	DefineConstMethod(IsInMeleeEngageRange, 0x86c02c, bool, Params(Go* unk1), Args(unk1));
	DefineConstMethod(IsInRange, 0x86bf2b, bool, Params(Go* unk1, float unk2), Args(unk1, unk2));
	DefineConstMethod(IsInRangedEngageRange, 0x86c045, bool, Params(Go* unk1), Args(unk1));
	DefineConstMethod(IsInSpellRange, 0x86bf9b, bool, Params(Go* unk1, Go* unk2), Args(unk1, unk2));
	DefineConstMethod(IsInTeleportRange, 0x86bf82, bool, Params(Go* unk1), Args(unk1));
	DefineConstMethod(IsInWeaponRange, 0x86bf4b, bool, Params(Go* unk1), Args(unk1));
	DefineConstMethod(IsLifeHigh, 0x86ada3, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsLifeLow, 0x86ad80, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsLosClear, 0x86a50d, bool, Params(Go* unk1), Args(unk1));
	DefineConstMethod(IsLosClear, 0x86a6c4, bool, Params(const SiegePos& unk1), Args(unk1));
	DefineConstMethod(IsManaHigh, 0x86c365, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(IsManaLow, 0x86c342, bool, NO_PARAMS, NO_ARGS);
	DefineMethod(IsMeleeSlotFree, 0x86c5bd, bool, Params(Go* unk1), Args(unk1));
	DefineConstMethod(IsRidingElevator, 0x86a0f3, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(MayAIInterrupt, 0x86ba59, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(MayAttackTarget, 0x868caf, bool, Params(const Go* unk1, bool unk2), Args(unk1, unk2));
	DefineMethod(MayAutoCastLifeDamagingSpell, 0x86f26b, bool, NO_PARAMS, NO_ARGS);
	DefineMethod(MayAutoCastLifeHealingSpell, 0x86f2fb, bool, NO_PARAMS, NO_ARGS);
	DefineMethod(MaySDoJob, 0x869e11, bool, Params(eJobAbstractType unk1), Args(unk1));
	DefineConstMethod(OnAlertProjectileNearMissedAttack, 0x41248f, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(OnAlertProjectileNearMissedFlee, 0x41249b, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(OnEnemyEnteredICZAttack, 0x4124a7, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(OnEnemyEnteredICZFlee, 0x4124b3, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(OnEnemyEnteredICZSwitchToMelee, 0x4124bd, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(OnEnemyEnteredOCZAttack, 0x4124c6, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(OnEnemyEnteredOCZFlee, 0x4124d1, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(OnEnemyEnteredWeaponEngageRangeAttack, 0x4124dd, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(OnEngagedFleedAbortAttack, 0x4124f5, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(OnEngagedLostConsciousnessAbortAttack, 0x412501, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(OnFriendEnteredOCZFlee, 0x4124e9, bool, NO_PARAMS, NO_ARGS);
	DefineMethod(RSAttack, 0x874012, bool, Params(const Goid_* unk1, eQPlace unk2, eActionOrigin unk3, bool unk4, const Goid_* unk5, int unk6), Args(unk1, unk2, unk3, unk4, unk5, unk6));
	DefineMethod(RSAttack, 0x411ef0, bool, Params(const Goid_* unk1, eQPlace unk2, eActionOrigin unk3, bool unk4, const Goid_* unk5), Args(unk1, unk2, unk3, unk4, unk5));
	DefineMethod(RSAttack, 0x411ed0, bool, Params(const Goid_* unk1, eQPlace unk2, eActionOrigin unk3, bool unk4), Args(unk1, unk2, unk3, unk4));
	DefineMethod(RSAttack, 0x411eb1, bool, Params(const Goid_* unk1, eQPlace unk2, eActionOrigin unk3), Args(unk1, unk2, unk3));
	DefineMethod(RSCast, 0x8741d0, bool, Params(const Goid_* unk1, const Goid_* unk2, eQPlace unk3, eActionOrigin unk4, const Goid_* unk5), Args(unk1, unk2, unk3, unk4, unk5));
	DefineMethod(RSCast, 0x411f0d, bool, Params(const Goid_* unk1, const Goid_* unk2, eQPlace unk3, eActionOrigin unk4), Args(unk1, unk2, unk3, unk4));
	DefineMethod(RSCastAtPosition, 0x874251, bool, Params(const SiegePos& unk1, const Goid_* unk2, eQPlace unk3, eActionOrigin unk4, const Goid_* unk5), Args(unk1, unk2, unk3, unk4, unk5));
	DefineMethod(RSCastAtPosition, 0x411f2b, bool, Params(const SiegePos& unk1, const Goid_* unk2, eQPlace unk3, eActionOrigin unk4), Args(unk1, unk2, unk3, unk4));
	DefineMethod(RSCollectLoot, 0x874318, bool, Params(eQPlace unk1, eActionOrigin unk2, const Goid_* unk3), Args(unk1, unk2, unk3));
	DefineMethod(RSCollectLoot, 0x411f6b, bool, Params(eQPlace unk1, eActionOrigin unk2), Args(unk1, unk2));
	DefineMethod(RSMove, 0x4121d8, bool, Params(const SiegePos& unk1, eQPlace unk2, eActionOrigin unk3, const Goid_* unk4), Args(unk1, unk2, unk3, unk4));
	DefineMethod(RSMove, 0x874869, bool, Params(const SiegePos& unk1, eQPlace unk2, eActionOrigin unk3, float unk4, const Goid_* unk5), Args(unk1, unk2, unk3, unk4, unk5));
	DefineMethod(RSMove, 0x4121b6, bool, Params(const SiegePos& unk1, eQPlace unk2, eActionOrigin unk3, float unk4), Args(unk1, unk2, unk3, unk4));
	DefineMethod(RSMove, 0x412195, bool, Params(const SiegePos& unk1, eQPlace unk2, eActionOrigin unk3), Args(unk1, unk2, unk3));
	DefineMethod(Send, 0x869ec7, bool, Params(const WorldMessage& unk1), Args(unk1));
	DefineMethod(SendDelayed, 0x869ef3, bool, Params(const WorldMessage& unk1, float unk2), Args(unk1, unk2));
	DefineMethod(SetJatCloneSource, 0x86d593, bool, Params(eJobAbstractType unk1, const gpbstring<char>& unk2), Args(unk1, unk2));
	DefineConstMethod(UnderstandsJob, 0x869de8, bool, Params(eJobAbstractType unk1), Args(unk1));
	DefineMethod(GetAttackTargetWeapon, 0x86c22d, Go*, Params(Go* unk1, bool unk2, bool unk3), Args(unk1, unk2, unk3));
	DefineMethod(GetAttackTargetWeapon, 0x411b5a, Go*, Params(Go* unk1), Args(unk1));
	DefineConstMethod(GetBestFocusEnemy, 0x86e7ec, Go*, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetClosestVisible, 0x411e07, Go*, Params(eQueryTrait unk1), Args(unk1));
	DefineConstMethod(GetClosestVisible, 0x86e44e, Go*, Params(float unk1, eQueryTrait unk2), Args(unk1, unk2));
	DefineConstMethod(GetClosestVisible, 0x86c16e, Go*, Params(float unk1, QtColl& unk2), Args(unk1, unk2));
	DefineConstMethod(GetClosestVisible, 0x411dee, Go*, Params(QtColl& unk1), Args(unk1));
	DefineConstMethod(GetClosestVisibleEnemy, 0x4141d6, Go*, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetClosestVisibleEnemy, 0x411e20, Go*, Params(bool unk1), Args(unk1));
	DefineConstMethod(GetClosestVisibleEnemy, 0x86e496, Go*, Params(float unk1, bool unk2), Args(unk1, unk2));
	DefineConstMethod(GetClosestVisibleFriend, 0x4141de, Go*, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetClosestVisibleFriend, 0x411e39, Go*, Params(bool unk1), Args(unk1));
	DefineConstMethod(GetClosestVisibleFriend, 0x86e525, Go*, Params(float unk1, bool unk2), Args(unk1, unk2));
	DefineConstMethod(GetClosestVisibleItemToLoot, 0x86ab95, Go*, Params(bool unk1), Args(unk1));
	DefineConstMethod(GetFarthestVisible, 0x86e6ef, Go*, Params(eQueryTrait unk1), Args(unk1));
	DefineConstMethod(GetFarthestVisible, 0x86d0ce, Go*, Params(QtColl& unk1), Args(unk1));
	DefineConstMethod(GetFarthestVisibleEnemy, 0x86e730, Go*, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetFarthestVisibleFriend, 0x86e79d, Go*, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetFarthestVisibleItem, 0x86e7e4, Go*, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetHighestVisibleAggro, 0x411bb2, Go*, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetHighestVisibleAggro, 0x411bef, Go*, Params(const Goid_* unk1), Args(unk1));
	DefineConstMethod(GetHighestVisibleAggro, 0x86eca8, Go*, Params(float unk1, float unk2, bool unk3, const Goid_* unk4), Args(unk1, unk2, unk3, unk4));
	DefineConstMethod(GetHighestVisibleAggro, 0x411bcd, Go*, Params(float unk1), Args(unk1));
	DefineMethod(GetOwningCoach, 0x4141c2, Go*, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetVisible, 0x86deaf, Go*, Params(eQueryTrait unk1, float unk2), Args(unk1, unk2));
	DefineConstMethod(GetVisible, 0x411ccc, Go*, Params(eQueryTrait unk1), Args(unk1));
	DefineConstMethod(GetVisible, 0x86c05e, Go*, Params(QtColl& unk1, float unk2), Args(unk1, unk2));
	DefineConstMethod(GetVisible, 0x411cb3, Go*, Params(QtColl& unk1), Args(unk1));
	DefineConstMethod(GetVisibleAtPosition, 0x86dfda, Go*, Params(const SiegePos& unk1, eQueryTrait unk2, float unk3), Args(unk1, unk2, unk3));
	DefineConstMethod(GetVisibleAtPosition, 0x411ce5, Go*, Params(const SiegePos& unk1, float unk2), Args(unk1, unk2));
	DefineConstMethod(GetVisibleAtPosition, 0x86c0d5, Go*, Params(const SiegePos& unk1, QtColl& unk2, float unk3), Args(unk1, unk2, unk3));
	DefineConstMethod(GetVisibleAtPosition, 0x411cfd, Go*, Params(const SiegePos& unk1), Args(unk1));
	DefineConstMethod(GetVisibleCastTarget, 0x8703fd, Go*, Params(Go* unk1, bool unk2, bool unk3, float unk4), Args(unk1, unk2, unk3, unk4));
	DefineConstMethod(GetVisibleCastTarget, 0x411db7, Go*, Params(Go* unk1, bool unk2, bool unk3), Args(unk1, unk2, unk3));
	DefineMethod(GetFrontActionStateName, 0x8715cf, gpbstring<char>, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetActionJobInQueue, 0x411ae4, Job*, Params(eJobAbstractType unk1), Args(unk1));
	DefineConstMethod(GetFrontJob, 0x869f80, Job*, Params(eJobQ unk1), Args(unk1));
	DefineConstMethod(GetJobInQueue, 0x869fb1, Job*, Params(eJobAbstractType unk1, eJobQ unk2), Args(unk1, unk2));
	DefineMethod(SDoJob, 0x871162, Job*, Params(const JobReq& unk1), Args(unk1));
	DefineConstMethod(GetPlayAttributes, 0x41234b, const JobAttributeBits&, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetAngryTarget, 0x411c54, const Goid_*, NO_PARAMS, NO_ARGS);
	DefineMethod(GetFrontActionGoalObject, 0x869fe3, const Goid_*, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetGuardTarget, 0x411b89, const Goid_*, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetHighestAggro, 0x411c0d, const Goid_*, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetHighestAggro, 0x86ee5e, const Goid_*, Params(float unk1, bool unk2, const Goid_* unk3), Args(unk1, unk2, unk3));
	DefineConstMethod(GetHighestAggro, 0x411c3c, const Goid_*, Params(float unk1, const Goid_* unk2), Args(unk1, unk2));
	DefineConstMethod(GetHighestAggro, 0x411c21, const Goid_*, Params(float unk1), Args(unk1));
	DefineConstMethod(GetLastEngagedObject, 0x411b8d, const Goid_*, NO_PARAMS, NO_ARGS);
	DefineMethod(UpdateLastEngagedObject, 0x86a056, const Goid_*, Params(const Goid_* unk1), Args(unk1));
	DefineMethod(GetEnemiesVisible, 0x411e84, const GoidColl&, NO_PARAMS, NO_ARGS);
	DefineMethod(GetFriendsVisible, 0x411e8b, const GoidColl&, NO_PARAMS, NO_ARGS);
	DefineMethod(GetItemsVisible, 0x411e92, const GoidColl&, NO_PARAMS, NO_ARGS);
	DefineMethod(GetFrontActionOrigin, 0x869ff5, eActionOrigin, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetDispositionOrders, 0x412336, eActorDisposition, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetHighestAggroType, 0x86c308, eAggroType, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetCombatOrders, 0x412328, eCombatOrders, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetFocusOrders, 0x41232f, eFocusOrders, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetFrontActionJat, 0x86887c, eJobAbstractType, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetLastEngagedJat, 0x411b94, eJobAbstractType, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetMatchingJob, 0x86f056, eJobAbstractType, Params(const JobAttributeBits& unk1), Args(unk1));
	DefineConstMethod(GetMatchingPlay, 0x86f0ea, eJobAbstractType, Params(const gpbstring<char>& unk1, const JobAttributeBits& unk2), Args(unk1, unk2));
	DefineConstMethod(GetMovementOrders, 0x412321, eMovementOrders, NO_PARAMS, NO_ARGS);
	DefineConstMethod(Get2DDistance, 0x86aa15, float, Params(Go* unk1), Args(unk1));
	DefineMethod(GetAggro, 0x86efe8, float, Params(const Goid_* unk1), Args(unk1));
	DefineConstMethod(GetAggroTypeGlobalScalar, 0x411bab, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetAggroTypeScalar, 0x86ec85, float, Params(eAggroType unk1), Args(unk1));
	DefineConstMethod(GetAngryDuration, 0x411c6d, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetAngryTimeLeft, 0x411c74, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetDistance, 0x86a802, float, Params(Go* unk1), Args(unk1));
	DefineConstMethod(GetDistanceAtPlanEnd, 0x86a81b, float, Params(Go* unk1), Args(unk1));
	DefineConstMethod(GetEngageRange, 0x868b08, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetFleeDistance, 0x41233d, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetHomeLeashDistance, 0x86c60c, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetIdealAttackDistance, 0x868d5c, float, Params(const Go* unk1), Args(unk1));
	DefineConstMethod(GetIdealMeleeAttackDistance, 0x868d29, float, Params(const Go* unk1), Args(unk1));
	DefineConstMethod(GetInnerComfortZoneRange, 0x412313, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetJumpRange, 0x4122c5, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetJumpSpeed, 0x4122cc, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetLimitedMovementRange, 0x4122be, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetLootRange, 0x41230c, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetMeleeEngageRange, 0x4122f4, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetMeleeWeaponRange, 0x868b9d, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetOuterComfortZoneRange, 0x41231a, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetPersonalSpaceRange, 0x412305, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetRangedEngageRange, 0x868dbc, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetSensorScanPeriod, 0x86c388, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetSightRange, 0x4122b7, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetTeleportRange, 0x4122ed, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetTimeElapsedSinceLastEnemySpotted, 0x86adc6, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetWeaponRange, 0x868b57, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetAllignedTeam, 0x868af7, int, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetEngagedMeAttackerCount, 0x86c3d4, int, Params(bool unk1), Args(unk1));
	DefineConstMethod(GetEngagedMeMeleeAttackerCount, 0x86c447, int, Params(bool unk1), Args(unk1));
	DefineConstMethod(GetEngagedMeMeleeSlotUsage, 0x86c542, int, Params(Go* unk1, bool unk2), Args(unk1, unk2));
	DefineConstMethod(GetEngagedMeRangedAttackerCount, 0x86c4cc, int, Params(bool unk1), Args(unk1));
	DefineConstMethod(GetMeleeSlotUsage, 0x412344, int, NO_PARAMS, NO_ARGS);
	DefineMethod(RCSetMayAttack, 0x868deb, FuBi::Cookie__*, Params(bool unk1, unsigned long unk2), Args(unk1, unk2));
	DefineMethod(RCSetMayAttackHeroes, 0x868ee2, FuBi::Cookie__*, Params(bool unk1, unsigned long unk2), Args(unk1, unk2));
	DefineMethod(RCSetMayBeAttacked, 0x868fd9, FuBi::Cookie__*, Params(bool unk1, unsigned long unk2), Args(unk1, unk2));
	DefineMethod(RCSetMayBeAttackedByHeroes, 0x8690d0, FuBi::Cookie__*, Params(bool unk1, unsigned long unk2), Args(unk1, unk2));
	DefineMethod(RSSetRank, 0x86869d, FuBi::Cookie__*, Params(unsigned long unk1), Args(unk1));
	DefineMethod(GetActorsInInnerComfortZone, 0x411ea3, GoidColl&, NO_PARAMS, NO_ARGS);
	DefineMethod(GetActorsInOuterComfortZone, 0x411eaa, GoidColl&, NO_PARAMS, NO_ARGS);
	DefineMethod(GetHomePosition, 0x868c61, SiegePos&, NO_PARAMS, NO_ARGS);
	DefineMethod(GetInitialPosition, 0x868c13, SiegePos&, NO_PARAMS, NO_ARGS);
	DefineMethod(GetLastExecutedUserAssignedActionPosition, 0x868bc5, SiegePos&, NO_PARAMS, NO_ARGS);
	DefineMethod(GetRank, 0x411b49, unsigned long, NO_PARAMS, NO_ARGS);
	DefineMethod(AddAggro, 0x874c60, void, Params(float unk1, const Goid_* unk2, eAggroType unk3), Args(unk1, unk2, unk3));
	DefineMethod(AddAggroToVisible, 0x875ef0, void, Params(float unk1, const Goid_* unk2, eAggroType unk3), Args(unk1, unk2, unk3));
	DefineMethod(AddAggroToVisibleEnemies, 0x874e61, void, Params(float unk1, const Goid_* unk2, eAggroType unk3), Args(unk1, unk2, unk3));
	DefineMethod(AddAggroToVisibleFriends, 0x874e05, void, Params(float unk1, const Goid_* unk2, eAggroType unk3), Args(unk1, unk2, unk3));
	DefineMethod(Clear, 0x869dcf, void, NO_PARAMS, NO_ARGS);
	DefineMethod(Clear, 0x869dba, void, Params(eJobQ unk1), Args(unk1));
	DefineMethod(ClearActions, 0x411b1f, void, NO_PARAMS, NO_ARGS);
	DefineMethod(ClearAggro, 0x8729a4, void, Params(const Goid_* unk1), Args(unk1));
	DefineMethod(ClearAllAggro, 0x86f01d, void, NO_PARAMS, NO_ARGS);
	DefineMethod(ClearAndCommit, 0x871138, void, Params(eJobQ unk1), Args(unk1));
	DefineMethod(ClearBrains, 0x411b17, void, NO_PARAMS, NO_ARGS);
	DefineMethod(GetPositionAtPlanEnd, 0x86a9c8, void, Params(SiegePos& unk1), Args(unk1));
	DefineMethod(MessageEngagedMe, 0x86d608, void, Params(const WorldMessage& unk1, const Goid_* unk2), Args(unk1, unk2));
	DefineMethod(MessageEngagedMe, 0x86f98f, void, Params(eWorldEvent unk1, const Goid_* unk2), Args(unk1, unk2));
	DefineMethod(MessageVisible, 0x86cda1, void, Params(const WorldMessage& unk1), Args(unk1));
	DefineMethod(RCSetCombatOrders, 0x86af04, void, Params(eCombatOrders unk1), Args(unk1));
	DefineMethod(RCSetDispositionOrders, 0x86b13e, void, Params(eActorDisposition unk1), Args(unk1));
	DefineMethod(RCSetFocusOrders, 0x86b021, void, Params(eFocusOrders unk1), Args(unk1));
	DefineMethod(RCSetLastEngagedObject, 0x868883, void, Params(const Goid_* unk1, eJobAbstractType unk2, unsigned long unk3), Args(unk1, unk2, unk3));
	DefineMethod(RCSetMovementOrders, 0x86ade7, void, Params(eMovementOrders unk1), Args(unk1));
	DefineMethod(RegisterFleeingFromMe, 0x874ebd, void, Params(const Goid_* unk1, float unk2), Args(unk1, unk2));
	DefineMethod(ResetAngryTarget, 0x868da8, void, NO_PARAMS, NO_ARGS);
	DefineMethod(RSCharge, 0x8742c0, void, Params(const Goid_* unk1, eQPlace unk2, eActionOrigin unk3, float unk4, const Goid_* unk5), Args(unk1, unk2, unk3, unk4, unk5));
	DefineMethod(RSCharge, 0x411f49, void, Params(const Goid_* unk1, eQPlace unk2, eActionOrigin unk3, float unk4), Args(unk1, unk2, unk3, unk4));
	DefineMethod(RSDoJob, 0x872d3b, void, Params(const JobReq& unk1), Args(unk1));
	DefineMethod(RSDoJobPacker, 0x87270e, void, Params(const_mem_ptr unk1), Args(unk1));
	DefineMethod(RSDrink, 0x8743be, void, Params(const Goid_* unk1, eQPlace unk2, eActionOrigin unk3, const Goid_* unk4), Args(unk1, unk2, unk3, unk4));
	DefineMethod(RSDrink, 0x411fa1, void, Params(const Goid_* unk1, eQPlace unk2, eActionOrigin unk3), Args(unk1, unk2, unk3));
	DefineMethod(RSDrinkLifeHealingPotion, 0x8709f3, void, Params(eActionOrigin unk1), Args(unk1));
	DefineMethod(RSDrinkManaHealingPotion, 0x870ae0, void, Params(eActionOrigin unk1), Args(unk1));
	DefineMethod(RSDrop, 0x874369, void, Params(const Goid_* unk1, const SiegePos& unk2, eQPlace unk3, eActionOrigin unk4, const Goid_* unk5), Args(unk1, unk2, unk3, unk4, unk5));
	DefineMethod(RSDrop, 0x411f83, void, Params(const Goid_* unk1, const SiegePos& unk2, eQPlace unk3, eActionOrigin unk4), Args(unk1, unk2, unk3, unk4));
	DefineMethod(RSDropGold, 0x875baf, void, Params(int unk1, const SiegePos& unk2, eQPlace unk3, eActionOrigin unk4), Args(unk1, unk2, unk3, unk4));
	DefineMethod(RSEquip, 0x874410, void, Params(const Goid_* unk1, eEquipSlot unk2, eQPlace unk3, eActionOrigin unk4, const Goid_* unk5), Args(unk1, unk2, unk3, unk4, unk5));
	DefineMethod(RSEquip, 0x411fbc, void, Params(const Goid_* unk1, eEquipSlot unk2, eQPlace unk3, eActionOrigin unk4), Args(unk1, unk2, unk3, unk4));
	DefineMethod(RSFace, 0x874465, void, Params(const Goid_* unk1, eQPlace unk2, eActionOrigin unk3, float unk4, const Goid_* unk5), Args(unk1, unk2, unk3, unk4, unk5));
	DefineMethod(RSFace, 0x411fda, void, Params(const Goid_* unk1, eQPlace unk2, eActionOrigin unk3, float unk4), Args(unk1, unk2, unk3, unk4));
	DefineMethod(RSFleeFromObject, 0x41201f, void, Params(const Goid_* unk1, eQPlace unk2, eActionOrigin unk3, const Goid_* unk4), Args(unk1, unk2, unk3, unk4));
	DefineMethod(RSFleeFromObject, 0x8744bd, void, Params(const Goid_* unk1, eQPlace unk2, eActionOrigin unk3, float unk4, int unk5, const Goid_* unk6), Args(unk1, unk2, unk3, unk4, unk5, unk6));
	DefineMethod(RSFleeFromObject, 0x41203f, void, Params(const Goid_* unk1, eQPlace unk2, eActionOrigin unk3, float unk4, int unk5), Args(unk1, unk2, unk3, unk4, unk5));
	DefineMethod(RSFleeFromObject, 0x411ffc, void, Params(const Goid_* unk1, eQPlace unk2, eActionOrigin unk3), Args(unk1, unk2, unk3));
	DefineMethod(RSFollow, 0x87451b, void, Params(const Goid_* unk1, eQPlace unk2, eActionOrigin unk3, float unk4, const Goid_* unk5), Args(unk1, unk2, unk3, unk4, unk5));
	DefineMethod(RSFollow, 0x412064, void, Params(const Goid_* unk1, eQPlace unk2, eActionOrigin unk3, float unk4), Args(unk1, unk2, unk3, unk4));
	DefineMethod(RSGatherAndUse, 0x875a17, void, Params(const_mem_ptr unk1, const Goid_* unk2, eQPlace unk3, eActionOrigin unk4), Args(unk1, unk2, unk3, unk4));
	DefineMethod(RSGatherAndUse, 0x87688f, void, Params(GoidColl& unk1, const Goid_* unk2, eQPlace unk3, eActionOrigin unk4), Args(unk1, unk2, unk3, unk4));
	DefineMethod(RSGet, 0x874573, void, Params(const Goid_* unk1, eQPlace unk2, eActionOrigin unk3, const Goid_* unk4), Args(unk1, unk2, unk3, unk4));
	DefineMethod(RSGet, 0x412086, void, Params(const Goid_* unk1, eQPlace unk2, eActionOrigin unk3), Args(unk1, unk2, unk3));
	DefineMethod(RSGive, 0x8745c5, void, Params(const Goid_* unk1, const Goid_* unk2, eQPlace unk3, eActionOrigin unk4, const Goid_* unk5), Args(unk1, unk2, unk3, unk4, unk5));
	DefineMethod(RSGive, 0x4120a1, void, Params(const Goid_* unk1, const Goid_* unk2, eQPlace unk3, eActionOrigin unk4), Args(unk1, unk2, unk3, unk4));
	DefineMethod(RSGuard, 0x87461a, void, Params(const Goid_* unk1, eQPlace unk2, eActionOrigin unk3, const Goid_* unk4), Args(unk1, unk2, unk3, unk4));
	DefineMethod(RSGuard, 0x4120bf, void, Params(const Goid_* unk1, eQPlace unk2, eActionOrigin unk3), Args(unk1, unk2, unk3));
	DefineMethod(RSHide, 0x87466c, void, Params(const SiegePos& unk1, eQPlace unk2, eActionOrigin unk3, const Goid_* unk4, const Goid_* unk5), Args(unk1, unk2, unk3, unk4, unk5));
	DefineMethod(RSHide, 0x4120da, void, Params(const SiegePos& unk1, eQPlace unk2, eActionOrigin unk3, const Goid_* unk4), Args(unk1, unk2, unk3, unk4));
	DefineMethod(RSJump, 0x8746eb, void, Params(const SiegePos& unk1, eQPlace unk2, eActionOrigin unk3, const Goid_* unk4, int unk5), Args(unk1, unk2, unk3, unk4, unk5));
	DefineMethod(RSJump, 0x412115, void, Params(const SiegePos& unk1, eQPlace unk2, eActionOrigin unk3, const Goid_* unk4), Args(unk1, unk2, unk3, unk4));
	DefineMethod(RSJump, 0x41212f, void, Params(const SiegePos& unk1, eQPlace unk2, eActionOrigin unk3, int unk4), Args(unk1, unk2, unk3, unk4));
	DefineMethod(RSJump, 0x4120f8, void, Params(const SiegePos& unk1, eQPlace unk2, eActionOrigin unk3), Args(unk1, unk2, unk3));
	DefineMethod(RSKnockback, 0x874790, void, Params(const Goid_* unk1, float unk2, float unk3, eQPlace unk4, eActionOrigin unk5, const Goid_* unk6), Args(unk1, unk2, unk3, unk4, unk5, unk6));
	DefineMethod(RSKnockback, 0x41214d, void, Params(const Goid_* unk1, float unk2, float unk3, eQPlace unk4, eActionOrigin unk5), Args(unk1, unk2, unk3, unk4, unk5));
	DefineMethod(RSListen, 0x874810, void, Params(const Goid_* unk1, bool unk2, eQPlace unk3, eActionOrigin unk4, const Goid_* unk5), Args(unk1, unk2, unk3, unk4, unk5));
	DefineMethod(RSListen, 0x412177, void, Params(const Goid_* unk1, bool unk2, eQPlace unk3, eActionOrigin unk4), Args(unk1, unk2, unk3, unk4));
	DefineMethod(RSMoveAppend, 0x412239, void, Params(const SiegePos& unk1, eQPlace unk2, eActionOrigin unk3, const Goid_* unk4), Args(unk1, unk2, unk3, unk4));
	DefineMethod(RSMoveAppend, 0x8748db, void, Params(const SiegePos& unk1, eQPlace unk2, eActionOrigin unk3, float unk4, const Goid_* unk5), Args(unk1, unk2, unk3, unk4, unk5));
	DefineMethod(RSMoveAppend, 0x412217, void, Params(const SiegePos& unk1, eQPlace unk2, eActionOrigin unk3, float unk4), Args(unk1, unk2, unk3, unk4));
	DefineMethod(RSMoveAppend, 0x4121f6, void, Params(const SiegePos& unk1, eQPlace unk2, eActionOrigin unk3), Args(unk1, unk2, unk3));
	DefineMethod(RSPatrol, 0x874960, void, Params(const SiegePos& unk1, eQPlace unk2, eActionOrigin unk3, const Goid_* unk4), Args(unk1, unk2, unk3, unk4));
	DefineMethod(RSPatrol, 0x412257, void, Params(const SiegePos& unk1, eQPlace unk2, eActionOrigin unk3), Args(unk1, unk2, unk3));
	DefineMethod(RSSendMessageToFrontAction, 0x86ce24, void, Params(eWorldEvent unk1, const Goid_* unk2, const Goid_* unk3, unsigned long unk4), Args(unk1, unk2, unk3, unk4));
	DefineMethod(RSSetCombatOrders, 0x875064, void, Params(eCombatOrders unk1), Args(unk1));
	DefineMethod(RSSetDispositionOrders, 0x875306, void, Params(eActorDisposition unk1), Args(unk1));
	DefineMethod(RSSetFocusOrders, 0x8751b5, void, Params(eFocusOrders unk1), Args(unk1));
	DefineMethod(RSSetMovementOrders, 0x874f13, void, Params(eMovementOrders unk1), Args(unk1));
	DefineMethod(RSSlide, 0x8749d1, void, Params(const SiegePos& unk1, float unk2, float unk3, eQPlace unk4, eActionOrigin unk5, const Goid_* unk6), Args(unk1, unk2, unk3, unk4, unk5, unk6));
	DefineMethod(RSSlide, 0x412272, void, Params(const SiegePos& unk1, float unk2, float unk3, eQPlace unk4, eActionOrigin unk5), Args(unk1, unk2, unk3, unk4, unk5));
	DefineMethod(RSStop, 0x874a8e, void, Params(eActionOrigin unk1), Args(unk1));
	DefineMethod(RSTeleport, 0x874ad6, void, Params(const SiegePos& unk1, eQPlace unk2, eActionOrigin unk3, const Goid_* unk4), Args(unk1, unk2, unk3, unk4));
	DefineMethod(RSTeleport, 0x41229c, void, Params(const SiegePos& unk1, eQPlace unk2, eActionOrigin unk3), Args(unk1, unk2, unk3));
	DefineMethod(RSUnEquip, 0x874b47, void, Params(eEquipSlot unk1, eQPlace unk2, eActionOrigin unk3), Args(unk1, unk2, unk3));
	DefineMethod(RSUse, 0x874b75, void, Params(const Goid_* unk1, eQPlace unk2, eActionOrigin unk3), Args(unk1, unk2, unk3));
	DefineMethod(SDisable, 0x875830, void, Params(bool unk1), Args(unk1));
	DefineMethod(SEnable, 0x875764, void, NO_PARAMS, NO_ARGS);
	DefineMethod(SetActorAutoFidgets, 0x412352, void, Params(bool unk1), Args(unk1));
	DefineMethod(SetActorWeaponPreference, 0x41245f, void, Params(eWeaponPreference unk1), Args(unk1));
	DefineMethod(SetAggroTypeGlobalScalar, 0x411b9b, void, Params(float unk1), Args(unk1));
	DefineMethod(SetAllignedTeam, 0x868afb, void, Params(int unk1), Args(unk1));
	DefineMethod(SetAngryTarget, 0x868d8f, void, Params(const Goid_* unk1, float unk2), Args(unk1, unk2));
	DefineMethod(SetGuardTarget, 0x411b6d, void, Params(const Goid_* unk1), Args(unk1));
	DefineMethod(SetHomePosition, 0x868c96, void, Params(const SiegePos& unk1), Args(unk1));
	DefineMethod(SetInitialPosition, 0x868c48, void, Params(const SiegePos& unk1), Args(unk1));
	DefineMethod(SetLastExecutedUserAssignedActionPosition, 0x868bfa, void, Params(const SiegePos& unk1), Args(unk1));
	DefineMethod(SetMayProcessAI, 0x41239f, void, Params(bool unk1), Args(unk1));
	DefineMethod(SetMayProcessSensors, 0x4123c4, void, Params(bool unk1), Args(unk1));
	DefineMethod(SetRank, 0x411b4d, void, Params(unsigned long unk1), Args(unk1));
	DefineMethod(SGatherAndUse, 0x874b9d, void, Params(GopColl& unk1, const Goid_* unk2, eQPlace unk3, eActionOrigin unk4), Args(unk1, unk2, unk3, unk4));
	DefineMethod(SSetMayAttack, 0x86b32b, void, Params(bool unk1), Args(unk1));
	DefineMethod(SSetMayAttackHeroes, 0x86b33c, void, Params(bool unk1), Args(unk1));
	DefineMethod(SSetMayBeAttacked, 0x86b34d, void, Params(bool unk1), Args(unk1));
	DefineMethod(SSetMayBeAttackedByHeroes, 0x86b35e, void, Params(bool unk1), Args(unk1));
	DefineMethod(UnregisterFleeingFromMe, 0x8729de, void, Params(const Goid_* unk1), Args(unk1));
	DefineMethod(UnregisterFleeingFromMeByDistance, 0x872a23, void, Params(float unk1), Args(unk1));
};
