#pragma once

class GoParty {
public:
	DefineStaticMethod(FUBI_NetToInstance, 0x412604, GoParty*, Params(unsigned long unk1, FuBi::Cookie__** unk2), Args(unk1, unk2));
	DefineStaticMethod(FUBI_InstanceToNet, 0x4125fb, unsigned long, Params(GoParty* unk1), Args(unk1));
	DefineMethod(GetFreeMode, 0x412581, bool, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetHoldingGround, 0x4125c3, bool, NO_PARAMS, NO_ARGS);
	DefineMethod(GetMembersAccordingToHealNeed, 0x87e63c, bool, Params(GoidColl& unk1, bool unk2, const Goid_* unk3), Args(unk1, unk2, unk3));
	DefineMethod(GetMembersAccordingToHealNeed, 0x87e562, bool, Params(GopColl& unk1, bool unk2), Args(unk1, unk2));
	DefineMethod(GetSpotPosition, 0x8807f1, bool, Params(const Goid_* unk1, SiegePos& unk2), Args(unk1, unk2));
	DefineConstMethod(IsInGuardStandingOrders, 0x4125af, bool, NO_PARAMS, NO_ARGS);
	DefineMethod(Move, 0x880925, bool, Params(const SiegePos& unk1, const vector_3& unk2, eQPlace unk3, eActionOrigin unk4, bool unk5, bool unk6, bool unk7, bool unk8, bool unk9), Args(unk1, unk2, unk3, unk4, unk5, unk6, unk7, unk8, unk9));
	DefineMethod(Move, 0x88089a, bool, Params(const SiegePos& unk1, eQPlace unk2, eActionOrigin unk3, bool unk4, bool unk5, bool unk6, bool unk7, bool unk8), Args(unk1, unk2, unk3, unk4, unk5, unk6, unk7, unk8));
	DefineMethod(Move, 0x8807fd, bool, Params(eQPlace unk1, eActionOrigin unk2, bool unk3, bool unk4, bool unk5, bool unk6, bool unk7), Args(unk1, unk2, unk3, unk4, unk5, unk6, unk7));
	DefineMethod(Regroup, 0x8809eb, bool, Params(eQPlace unk1), Args(unk1));
	DefineMethod(GetFormation, 0x41256d, Formation*, NO_PARAMS, NO_ARGS);
	DefineMethod(GetPreferredMemberSacrifice, 0x8794eb, const Goid_*, NO_PARAMS, NO_ARGS);
	DefineMethod(GetTalkingDisband, 0x412588, const Goid_*, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetStandingOrders, 0x87871e, eStandingOrders, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetDefaultPartyLightInnerRadius, 0x41259f, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetDefaultPartyLightOuterRadius, 0x4125a3, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetDefaultPartyLightVertOffset, 0x4125a7, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetPartyLightInnerRadius, 0x41258f, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetPartyLightOuterRadius, 0x412593, float, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetPartyLightVertOffset, 0x412597, float, NO_PARAMS, NO_ARGS);
	DefineMethod(GetMaxMeleeSlotsPerChar, 0x4125d8, int, NO_PARAMS, NO_ARGS);
	DefineMethod(GetWaitingToJoinCount, 0x4141e6, int, NO_PARAMS, NO_ARGS);
	DefineMethod(GetTempGopCollA, 0x4125df, GopColl&, NO_PARAMS, NO_ARGS);
	DefineMethod(GetTempGopCollB, 0x4125e6, GopColl&, NO_PARAMS, NO_ARGS);
	DefineMethod(GetTempGopCollC, 0x4125ed, GopColl&, NO_PARAMS, NO_ARGS);
	DefineMethod(GetTempQtColl1, 0x4125f4, QtColl&, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetDefaultPartyLightColor, 0x4125ab, unsigned long, NO_PARAMS, NO_ARGS);
	DefineConstMethod(GetPartyLightColor, 0x41259b, unsigned long, NO_PARAMS, NO_ARGS);
	DefineMethod(AddMemberNow, 0x87b047, void, Params(Go* unk1), Args(unk1));
	DefineMethod(GetFocusThenMembersAccordingToRank, 0x87e0bb, void, Params(GoidColl& unk1, const Goid_* unk2), Args(unk1, unk2));
	DefineMethod(GetMembersAccordingToRank, 0x87dffb, void, Params(GoidColl& unk1, const Goid_* unk2), Args(unk1, unk2));
	DefineMethod(GetMembersAccordingToRank, 0x87e715, void, Params(GopColl& unk1), Args(unk1));
	DefineMethod(RCAddMemberNow, 0x87b78e, void, Params(Go* unk1), Args(unk1));
	DefineMethod(RCRemoveMemberNow, 0x87a406, void, Params(Go* unk1), Args(unk1));
	DefineMethod(RCSetTalkingDisband, 0x8785e8, void, Params(const Goid_* unk1), Args(unk1));
	DefineMethod(RemoveMemberNow, 0x879488, void, Params(Go* unk1), Args(unk1));
	DefineMethod(RSAddMemberNow, 0x87b904, void, Params(Go* unk1), Args(unk1));
	DefineMethod(RSRemoveMemberNow, 0x87b0b0, void, Params(Go* unk1), Args(unk1));
	DefineMethod(RSSetFormationDirection, 0x87b203, void, Params(const vector_3& unk1), Args(unk1));
	DefineMethod(RSSetFormationPosition, 0x87a61e, void, Params(const SiegePos& unk1), Args(unk1));
	DefineMethod(RSSetHoldingGround, 0x87a516, void, Params(bool unk1), Args(unk1));
	DefineMethod(RSSetStandingOrders, 0x880aaf, void, Params(eStandingOrders unk1), Args(unk1));
	DefineMethod(RSSetTalkingDisband, 0x879558, void, Params(const Goid_* unk1), Args(unk1));
	DefineMethod(SetFreeMode, 0x412571, void, Params(bool unk1), Args(unk1));
	DefineMethod(SetPartyLightValues, 0x8786cd, void, Params(float unk1, float unk2, float unk3, unsigned long unk4), Args(unk1, unk2, unk3, unk4));
};
